<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * How to represent the contract denomination
 */
enum Bm2ContractRepresentationOption: int
{
    /**
     * Use the symbols for clubs, diamonds, hearts and spades
     */
    case UseSymbols = 0;
    /**
     * Use letters for the denominations
     */
    case UseLetter = 1;
}
