<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether and when the players can enter the handrecord for a board.
 */
enum Bm2EnterHandrecordWhenOption: int
{
    /**
     * The handrecord can be entered at the end of each round.
     */
    case AtEndOfRound = 0;
    /**
     * The handrecord can be entered after the play of each board.
     */
    case AtEndOfBoard = 1;
    /**
     * The handrecord cannot be entered.
     */
    case DoNotEnter = 2;
}
