<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies which source data should be consulted to look up player names for player numbers.
 */
enum Bm2NameSource: int
{
    /**
     * The PlayerNames table of the .bws scoring file.
     */
    case PlayerNamesTable = 0;
    /**
     * A separate MS-Access table.
     */
    case BMPlayerDB = 1;
    /**
     * No External source.
     */
    case NoExternalSource = 2;
    /**
     * First check the PlayerNames table then the external MS-Access file.
     */
    case PlayerNamesTableThenBMPlayerDB = 3;
}
