<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies for which organization an entered playernumber should be validated.
 */
enum Bm2NumberValidationOption: int
{
    /**
     * No validation.
     */
    case NoValidation = 0;
    /**
     * Validate for the ACBL (USA).
     */
    case ACBL = 1;
    /**
     * Validate for the FFB (France).
     */
    case FFB = 2;
    /**
     * Validate for the ABF (Australia).
     */
    case ABF = 3;
    /**
     * Validate for the JCBL (Japanese).
     */
    case JCBL = 4;
}
