<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies if the pairnumber should be part of entering the contract.
 */
enum Bm2PairNumberEntryOption: int
{
    /**
     * The pairnumber cannot be entered.
     */
    case NoEntry = 0;
    /**
     * The pairnumber entry is optional.
     */
    case Optional = 1;
    /**
     * The pairnumber entry is required.
     */
    case Required = 2;
}
