<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Show the pointscore sign (plus or minus) from the perspective of declarer or North-South.
 */
enum Bm2PointScorePerspectiveOption: int
{
    /**
     * Show the pointscore sign (plus or minus) from the perspective of North-South.
     */
    case FromNorthSouth = 0;
    /**
     * Show the pointscore sign (plus or minus) from the perspective of declarer.
     */
    case FromDeclarer = 1;
}
