<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * How the results on a board should be formatted.
 */
enum Bm2ResultsOverviewOption: int
{
    /**
     * Group the results by pointscore and declarer: Max 6 lines, 1 column.
     */
    case FrequencyList6lines1column = 0;
    /**
     * Group the results by pointscore and declarer: Max 6 lines of 2 columns.
     */
    case FrequencyList6lines2columns = 1;
    /**
     * Group the results by pointscore and declarer: Max 4 lines, 1 column.
     */
    case FrequencyList4lines1column = 2;
    /**
     * Show the result for each couple of competing pairs: Max 6 lines, 1 column.
     */
    case Traveler6lines1column = 3;
    /**
     * Show the result for each couple of competing pairs: Max 6 lines, 2 columns.
     */
    case Traveler6lines2columns = 4;
    /**
     * Show the result for each couple of competing pairs: Max 4 lines, 1 column.
     */
    case Traveler4lines1column = 5;
}
