<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * How to enter the resulting tricks of a contract
 */
enum BM2ResultEntryMethod: int
{
    /**
     * The number of tricks above or below the level of the contract.
     */
    case UpDownTricks = 0;
    /**
     * The total number of tricks.
     */
    case NumberOfTricks = 1;
    /**
     * American style.
     */
    case AmericanStyle = 2;
}
