<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether and when to show the ranking.
 */
enum Bm2ShowRankingOption: int
{
    /**
     * Do not show.
     */
    case DoNotShow = 0;
    /**
     * Show the ranking after each round.
     */
    case ShowAllRounds = 1;
    /**
     * Show the ranking after the last round only.
     */
    case ShowAfterLastRound = 2;
}
