<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether and how to show the summary points after the last round.
 */
enum Bm2SummaryPointOption: int
{
    /**
     * Show the scores as matchpoints.
     */
    case Matchpoints = 0;
    /**
     * Show the scores a percentages.
     */
    case Percentage = 1;
    /**
     * Do not show.
     */
    case NoSummary = -1;
}
