<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether and when to show the names of the competing pairs.
 */
enum Bm2ShowPlayerNamesOption: int
{
    /**
     * Do not show.
     */
    case DoNotShow = 0;
    /**
     * Show in all rounds.
     */
    case ShowInAllRounds = 1;
    /**
     * Show in first round only.
     */
    case ShowInFirstRoundOnly = 2;
}
