<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies if a not played entry must be confirmed by the TD
 */
enum Bm3ConfirmNPOption: int
{
    /**
     * TD must not confirm Not Played
     */
    case Disabled = 0;
    /**
     * TD must confirm Not Played
     */
    case Enabled = 1;
}
