<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether the Bridgemates for the section will work in online mode (continuous communication
 * with the Bridgemate 3 server) or if they work in offline mode (communication only at the start and
 * the end of the session).
 */
enum Bm3ConnectionModeOption: int
{
    /**
     * The Bridgemates for the section will work in online mode (continuous communication with the
     * Bridgemate 3 server).
     */
    case Online = 0;
    /**
     * The Bridgemates for the section will work in offline mode (communication will be initiated at
     * the end of the session or can be initiated manually).
     */
    case Offline = 1;
}
