<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether and when handrecords can be entered by the players.
 */
enum Bm3EnterHandrecordOption: int
{
    /**
     * Handrecords cannot be entered by the players.
     */
    case Disabled = 0;
    /**
     * Handrecords can be entered after play of the board.
     */
    case AtEndOfBoard = 1;
    /**
     * Handrecords can be entered at the end of the round.
     */
    case AtEndOfRound = 2;
}
