<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether the lead card must be entered and how this will be validated.
 */
enum Bm3LeadCardEntryOption: int
{
    /**
     * No lead card entry.
     */
    case Disabled = 0;
    /**
     * The lead card must be entered. It will not be validated against the handrecord.
     */
    case EnabledNoValidation = 1;
    /**
     * The lead card must be entered. It will be validated against the handrecord and it must be
     * changed if validation fails.
     */
    case EnabledWithValidationMustComply = 2;
    /**
     * The lead card must be entered. It will be validated against the handrecord and a warning is
     * issued if validation fails.
     */
    case EnabledWithValidationAllowNonCompliance = 3;
}
