<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies which language should be used on the Bridgemate.
 */
enum Bm3LanguageOption: int
{
    /**
     * English
     */
    case English = 0;
    /**
     * Dutch
     */
    case Dutch = 1;
    /**
     * French
     */
    case French = 2;
    /**
     * German
     */
    case German = 3;
    /**
     * Italian
     */
    case Italian = 4;
    /**
     * Danish
     */
    case Danish = 5;
    /**
     * Spanish
     */
    case Spanish = 6;
    /**
     * Norwegian
     */
    case Norwegian = 7;
    /**
     * Polish
     */
    case Polish = 8;
    /**
     * Swedish
     */
    case Swedish = 9;
    /**
     * Turkish
     */
    case Turkish = 10;
}
