<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether the tables for the next round should be displayed after the current round ends.
 */
enum Bm3NextRoundSeatingOption: int
{
    /**
     * Do not display the tables for the next round.
     */
    case Disabled = 0;
    /**
     * Display the tables for the next round after the current round ends.
     */
    case Enabled = 1;
}
