<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies wheter and when players can make themselves known.
 */
enum Bm3PlayerRegistrationOption: int
{
    /**
     * Player cannot make themselves known by entering their detaiils.
     */
    case Disabled = 0;
    /**
     * Player can make themselves known by entering their details in the first round only.
     */
    case FirstRoundOnly = 1;
    /**
     * Player can make themselves known by entering their details in all rounds.
     */
    case AllRounds = 2;
}
