<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether player can make themselves known once the round has started.
 */
enum Bm3PlayerRegistrationOptionDuringPlay: int
{
    /**
     * Players can make themselved known at the start of the round, before any result has been entered.
     */
    case Disabled = 0;
    /**
     * Players can make themselves known during any stage of the round.
     */
    case Enabled = 1;
}
