<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies how the wind rose player view is displayed
 */
enum BM3PlayerViewOption: int
{
    /**
     * players are displayed with north at the top
     */
    case NorthOnTop = 0;
    /**
     * players are displayed with north at the bottom
     */
    case NorthOnTheBottom = 1;
}
