<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Players must identify themselves at the start of the session by entering their playernumber.
 */
enum Bm3PlayerNumberMandatoryOption: int
{
    /**
     * Indicates that the feature or functionality is disabled.
     */
    case Disabled = 0;
    /**
     * Inidcates that the feature is enabled.
     */
    case Enabled = 1;
}
