<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether the result for a board can be changed after both pairs have confirmed it.
 */
enum Bm3ResultReentryOption: int
{
    /**
     * The result for a board cannot be changed after both pairs have confirmed it.
     */
    case Disabled = 0;
    /**
     * The result for a board can be changed after both pairs have confirmed it.
     */
    case Enabled = 1;
}
