<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether and when the ranking can be consulted.
 */
enum Bm3RankingDisplayOption: int
{
    /**
     * The ranking cannot be consulted.
     */
    case Disabled = 0;
    /**
     * The ranking can be consulted at the end of each round.
     */
    case EndOfEachRound = 1;
    /**
     * The ranking can be consulted at the end of the last round.
     */
    case EndOfSession = 2;
    /**
     * The ranking can be consulted at any moment.
     */
    case Always = 3;
}
