<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies how the number of tricks obtained must be entered.
 */
enum Bm3ResultEntryMethod: int
{
    /**
     * Enter the number of tricks obtained relative to the contract level.
     */
    case UpDownTricks = 0;
    /**
     * Enter the total number of tricks obtained.
     */
    case NumberOfTricks = 1;
    /**
     * Enter the number of tricks obtained American style.
     */
    case AmericanStyle = 2;
}
