<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies if there should be one column (for NS only) or two (for both NS and EW).
 */
enum Bm3ScoreColumnOption: int
{
    /**
     * Show one column, for NS.
     */
    case NorthSouthOnly = 0;
    /**
     * Shpw two columns, for NS and EW.
     */
    case NorthSouthAndEastWest = 1;
}
