<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether starting positions should be confirmed by players at start of the session
 */
enum BM3StartingPositionsOption: int
{
    /**
     * Players cannot / may no confirm starting positions (NE/SW) at start of the session
     */
    case Disabled = 0;
    /**
     * Players must confirm starting positions (NE/SW) at start of the session
     */
    case Enabled = 1;
}
