<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether session summaries are enabled or disabled.
 */
enum Bm3SessionSummaryOption: int
{
    /**
     * Indicates that the feature or functionality is disabled.
     */
    case Disabled = 0;
    /**
     * Indicates that the feature or functionality is enabled.
     */
    case Enabled = 1;
}
