<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies if all the results obtained in the round can be consulted.
 */
enum Bm3ScoreRecapOption: int
{
    /**
     * The results obtained in the round cannot be consulted.
     */
    case Disabled = 0;
    /**
     * The results obtained in the round can be consulted at the end of the round only.
     */
    case EnabledAtEndOfRoundOnly = 1;
    /**
     * The results obtained in the round can be consulted at any time.
     */
    case Always = 2;
}
