<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies of the players can call the TD using the Bridgemate.
 */
enum Bm3TdCallOption: int
{
    /**
     * The players cannot call the TD using the Bridgemate.
     */
    case Disabled = 0;
    /**
     * The players can call the TD using the Bridgemate.
     */
    case Enabled = 1;
}
