<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies wheter to include the own score for a board in the result overview.
 */
enum Bm3ViewPercentagesOption: int
{
    /**
     * Do not include the own score for a board in the result overview.
     */
    case Disabled = 0;
    /**
     * Include the own score for a board in the result overview.
     */
    case Enabled = 1;
}
