<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies whether players can consult the handrecord for a board they just played.
 */
enum Bm3ViewHandrecordOption: int
{
    /**
     * Handrecords cannot be consulted.
     */
    case Disabled = 0;
    /**
     * Handrecords can be consulted after play of the board.
     */
    case Enabled = 1;
}
