<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies if other results on the board can be viewed.
 */
enum Bm3ViewResultsOption: int
{
    /**
     * Other results on the board cannot be viewed.
     */
    case Disabled = 0;
    /**
     * Only the own result can be viewed.
     */
    case OwnResultOnly = 1;
    /**
     * Other results, including the own results, on the board can be viewed.
     */
    case OwnResultAndOtherResults = 2;
    /**
     * Results shown at the end of the round in the board overview.
     */
    case AtEndOfRound = 3;
}
