<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Contains all settings for the Bridgemate 3 for a section. Mind that all values must be supplied.
 */
class Bridgemate3SettingsDTO extends BridgemateSettingsDTO
{
    /**
     * Valid values 1-7. Defines the screen brightness.
     */
    public int $BM3ScreenBrightness = 0;

    /**
     * Valid values 0-15. Defines the number of seconds(times 5) before the screen of the Bridgemate
     * will dim.So the default value of 2 amounts to 10 seconds.
     */
    public int $BM3ScreenDimMode = 0;

    /**
     * Valid values 0-15. Defines the number of seconds (times 5) before the screen of the Bridgemate
     * will turn off. A value of zero, the default, means "never turn off".
     */
    public int $BM3ScreenOffMode = 0;

    /**
     * Valid values 0-120. Defines the number of seconds (times 5) before the Bridgemate will enter
     * Sleepmode. Once the Bridgemate has entered sleepmode its powerbutton must be used to wake it up
     * again.
     */
    public int $BM3SleepMode = 0;

    /**
     * Valid values 0-7. Currently not in use.
     */
    public int $BM3AudioVolume = 0;

    /**
     * Specifies which language the Bridgemate will use. The default is zero for English.
     */
    public Bm3LanguageOption $BM3Language = Bm3LanguageOption::English;

    /**
     * Must be four digits. The code the TD must enter to get access to the TD menu. Defaults to
     * "0000".
     */
    public ?string $BM3PINcode = null;

    /**
     * Specifies if the TD must confirm a "Not Played". Default Off
     */
    public Bm3ConfirmNPOption $BM3ConfirmNP = Bm3ConfirmNPOption::Disabled;

    /**
     * Specifies if players can call for the Tournament Director using the Bridgemate.
     */
    public Bm3TdCallOption $BM3TDCall = Bm3TdCallOption::Disabled;

    /**
     * Specifies how players can enter the result for a board: Up/Down tricks, total tricks or American
     * style.
     */
    public Bm3ResultEntryMethod $BM3ResultMethod = Bm3ResultEntryMethod::UpDownTricks;

    /**
     * Specifies if players may reenter the result of the board after the original entry has been
     * confirmed by the opponents.
     */
    public Bm3ResultReentryOption $BM3BoardResultReentry = Bm3ResultReentryOption::Disabled;

    /**
     * Specifies if the leadcard must be enterd together with the contract and if the leadcard should
     * be validated againts the handrecord.
     */
    public Bm3LeadCardEntryOption $BM3LeadCardEntry = Bm3LeadCardEntryOption::Disabled;

    /**
     * Specifies if and when the players can make themselves known by entering their playernumber
     * and/or name on the Bridgemate.
     */
    public Bm3PlayerRegistrationOption $BM3PlayerNumberEntry = Bm3PlayerRegistrationOption::Disabled;

    /**
     * Specifies if and when the players can make themselves known by entering their playernumber
     * and/or name on the Bridgemate while the round is in progress (i.e.: after a board has been
     * entered).
     */
    public Bm3PlayerRegistrationOptionDuringPlay $BM3PlayerNumberEntryDuringPlay = Bm3PlayerRegistrationOptionDuringPlay::Disabled;

    /**
     * Specifies if players must identify themselves at the start of the session by entering their
     * playernumber.
     */
    public Bm3PlayerNumberMandatoryOption $BM3PlayerNumberMandatory = Bm3PlayerNumberMandatoryOption::Disabled;

    /**
     * Specifies whether starting positions should be confirmed by players at start of the session
     */
    public BM3StartingPositionsOption $BM3StartingPositions = BM3StartingPositionsOption::Disabled;

    /**
     * Specifies how the wind rose player view is displayed
     */
    public BM3PlayerViewOption $BM3PlayerView = BM3PlayerViewOption::NorthOnTop;

    /**
     * Specifies if and when the Bridgemate will show the current ranking for the players on the table.
     */
    public Bm3RankingDisplayOption $BM3Ranking = Bm3RankingDisplayOption::Disabled;

    /**
     * Specifes if the seatings for the next round must be displayed after the last result has been
     * entered for the round.
     */
    public Bm3NextRoundSeatingOption $BM3NextSeatings = Bm3NextRoundSeatingOption::Disabled;

    /**
     * Specifies if and when the Bridgemate will show a recap of the scores obtained on the table in
     * the current round.
     */
    public Bm3ScoreRecapOption $BM3ScoreRecap = Bm3ScoreRecapOption::Disabled;

    /**
     * Specifies if the Bridgemate will show the other results for the board that was just entered.
     */
    public Bm3ViewResultsOption $BM3ViewResults = Bm3ViewResultsOption::Disabled;

    /**
     * Specifies if the Bridgemate will show a session summary with all the scores obtained in the
     * session once the session has ended.
     */
    public Bm3SessionSummaryOption $BM3SessionSummary = Bm3SessionSummaryOption::Disabled;

    /**
     * Specifies if the score columns should be for NS only (one column) or for NS and EW (two columns)
     */
    public Bm3ScoreColumnOption $BM3ScoreColum = Bm3ScoreColumnOption::NorthSouthOnly;

    /**
     * Specifies if the own percentage should be included in the results overview.
     */
    public Bm3ViewPercentagesOption $BMViewPercentages = Bm3ViewPercentagesOption::Disabled;

    /**
     * Specifies if players may view the handrecord after the result has been entered.
     */
    public Bm3ViewHandrecordOption $BM3ViewHandrecord = Bm3ViewHandrecordOption::Disabled;

    /**
     * Specifies if and when the players can enter the handrecord for a board if it is not present.
     */
    public Bm3EnterHandrecordOption $BM3EnterHandrecord = Bm3EnterHandrecordOption::Disabled;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'ValidationMessages' => $this->ValidationMessages,
            'BM3ScreenBrightness' => $this->BM3ScreenBrightness,
            'BM3ScreenDimMode' => $this->BM3ScreenDimMode,
            'BM3ScreenOffMode' => $this->BM3ScreenOffMode,
            'BM3SleepMode' => $this->BM3SleepMode,
            'BM3AudioVolume' => $this->BM3AudioVolume,
            'BM3Language' => $this->BM3Language,
            'BM3PINcode' => $this->BM3PINcode,
            'BM3ConfirmNP' => $this->BM3ConfirmNP,
            'BM3TDCall' => $this->BM3TDCall,
            'BM3ResultMethod' => $this->BM3ResultMethod,
            'BM3BoardResultReentry' => $this->BM3BoardResultReentry,
            'BM3LeadCardEntry' => $this->BM3LeadCardEntry,
            'BM3PlayerNumberEntry' => $this->BM3PlayerNumberEntry,
            'BM3PlayerNumberEntryDuringPlay' => $this->BM3PlayerNumberEntryDuringPlay,
            'BM3PlayerNumberMandatory' => $this->BM3PlayerNumberMandatory,
            'BM3StartingPositions' => $this->BM3StartingPositions,
            'BM3PlayerView' => $this->BM3PlayerView,
            'BM3Ranking' => $this->BM3Ranking,
            'BM3NextSeatings' => $this->BM3NextSeatings,
            'BM3ScoreRecap' => $this->BM3ScoreRecap,
            'BM3ViewResults' => $this->BM3ViewResults,
            'BM3SessionSummary' => $this->BM3SessionSummary,
            'BM3ScoreColum' => $this->BM3ScoreColum,
            'BMViewPercentages' => $this->BMViewPercentages,
            'BM3ViewHandrecord' => $this->BM3ViewHandrecord,
            'BM3EnterHandrecord' => $this->BM3EnterHandrecord,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        $dto->BM3ScreenBrightness = $data['BM3ScreenBrightness'] ?? 0;
        $dto->BM3ScreenDimMode = $data['BM3ScreenDimMode'] ?? 0;
        $dto->BM3ScreenOffMode = $data['BM3ScreenOffMode'] ?? 0;
        $dto->BM3SleepMode = $data['BM3SleepMode'] ?? 0;
        $dto->BM3AudioVolume = $data['BM3AudioVolume'] ?? 0;
        $dto->BM3Language = Bm3LanguageOption::tryFrom($data['BM3Language'] ?? 0) ?? Bm3LanguageOption::English;
        $dto->BM3PINcode = $data['BM3PINcode'] ?? null;
        $dto->BM3ConfirmNP = Bm3ConfirmNPOption::tryFrom($data['BM3ConfirmNP'] ?? 0) ?? Bm3ConfirmNPOption::Disabled;
        $dto->BM3TDCall = Bm3TdCallOption::tryFrom($data['BM3TDCall'] ?? 0) ?? Bm3TdCallOption::Disabled;
        $dto->BM3ResultMethod = Bm3ResultEntryMethod::tryFrom($data['BM3ResultMethod'] ?? 0) ?? Bm3ResultEntryMethod::UpDownTricks;
        $dto->BM3BoardResultReentry = Bm3ResultReentryOption::tryFrom($data['BM3BoardResultReentry'] ?? 0) ?? Bm3ResultReentryOption::Disabled;
        $dto->BM3LeadCardEntry = Bm3LeadCardEntryOption::tryFrom($data['BM3LeadCardEntry'] ?? 0) ?? Bm3LeadCardEntryOption::Disabled;
        $dto->BM3PlayerNumberEntry = Bm3PlayerRegistrationOption::tryFrom($data['BM3PlayerNumberEntry'] ?? 0) ?? Bm3PlayerRegistrationOption::Disabled;
        $dto->BM3PlayerNumberEntryDuringPlay = Bm3PlayerRegistrationOptionDuringPlay::tryFrom($data['BM3PlayerNumberEntryDuringPlay'] ?? 0) ?? Bm3PlayerRegistrationOptionDuringPlay::Disabled;
        $dto->BM3PlayerNumberMandatory = Bm3PlayerNumberMandatoryOption::tryFrom($data['BM3PlayerNumberMandatory'] ?? 0) ?? Bm3PlayerNumberMandatoryOption::Disabled;
        $dto->BM3StartingPositions = BM3StartingPositionsOption::tryFrom($data['BM3StartingPositions'] ?? 0) ?? BM3StartingPositionsOption::Disabled;
        $dto->BM3PlayerView = BM3PlayerViewOption::tryFrom($data['BM3PlayerView'] ?? 0) ?? BM3PlayerViewOption::NorthOnTop;
        $dto->BM3Ranking = Bm3RankingDisplayOption::tryFrom($data['BM3Ranking'] ?? 0) ?? Bm3RankingDisplayOption::Disabled;
        $dto->BM3NextSeatings = Bm3NextRoundSeatingOption::tryFrom($data['BM3NextSeatings'] ?? 0) ?? Bm3NextRoundSeatingOption::Disabled;
        $dto->BM3ScoreRecap = Bm3ScoreRecapOption::tryFrom($data['BM3ScoreRecap'] ?? 0) ?? Bm3ScoreRecapOption::Disabled;
        $dto->BM3ViewResults = Bm3ViewResultsOption::tryFrom($data['BM3ViewResults'] ?? 0) ?? Bm3ViewResultsOption::Disabled;
        $dto->BM3SessionSummary = Bm3SessionSummaryOption::tryFrom($data['BM3SessionSummary'] ?? 0) ?? Bm3SessionSummaryOption::Disabled;
        $dto->BM3ScoreColum = Bm3ScoreColumnOption::tryFrom($data['BM3ScoreColum'] ?? 0) ?? Bm3ScoreColumnOption::NorthSouthOnly;
        $dto->BMViewPercentages = Bm3ViewPercentagesOption::tryFrom($data['BMViewPercentages'] ?? 0) ?? Bm3ViewPercentagesOption::Disabled;
        $dto->BM3ViewHandrecord = Bm3ViewHandrecordOption::tryFrom($data['BM3ViewHandrecord'] ?? 0) ?? Bm3ViewHandrecordOption::Disabled;
        $dto->BM3EnterHandrecord = Bm3EnterHandrecordOption::tryFrom($data['BM3EnterHandrecord'] ?? 0) ?? Bm3EnterHandrecordOption::Disabled;
        return $dto;
    }
}
