<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * The base class for the Bridgemate2SettingsDTO and the Bridgemate3SettingsDTO
 */
abstract class BridgemateSettingsDTO implements \JsonSerializable
{
    /**
     * Required. Specifies the guid of the session for which the settings apply.
     */
    public ?string $SessionGuid = null;

    /**
     * Required. Specifies for which section the settings apply.
     */
    public ?string $SectionLetters = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;
}
