<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Contains all settings for the Bridgemate 2 for a section. Mind that all values must be supplied.
 */
class Bridgemate2SettingsDTO extends BridgemateSettingsDTO
{
    /**
     * Show results obtained on other rounds and on other tables.
     */
    public bool $ShowResults = false;

    /**
     * Include the own result in the results overview.
     */
    public bool $ShowOwnResult = false;

    /**
     * Ask after showing the results if the overview should be repeated.
     */
    public bool $RepeatResults = false;

    /**
     * Show percentage rather than matchpoints.
     */
    public bool $ShowPercentage = false;

    /**
     * Currently not supported. Use the ScoringGroupDTO to group sections.
     */
    public bool $GroupSections = false;

    /**
     * Show the point score of a result from the declarer's perspective or from that of North-South.
     */
    public Bm2PointScorePerspectiveOption $ScorePoints = Bm2PointScorePerspectiveOption::FromNorthSouth;

    /**
     * Defines the way resulting tricks are enterd after the board has been played.
     */
    public BM2ResultEntryMethod $EnterResultsMethod = BM2ResultEntryMethod::UpDownTricks;

    /**
     * Determines if the pairnumbers are shown at the top of the Bridgemate.
     */
    public bool $ShowPairNumbers = false;

    /**
     * Currently not supported.
     */
    public bool $IntermediateResults = false;

    /**
     * The time in seconds before the Bridgemate will power off.
     */
    public int $AutopoweroffTime = 0;

    /**
     * The time in seconds that the message that the opponents must confirm the entered result is
     * shown.
     */
    public int $VerificationTime = 0;

    /**
     * Show the denomination of the contract as letters or as suit symbols.
     */
    public Bm2ContractRepresentationOption $ShowContract = Bm2ContractRepresentationOption::UseSymbols;

    /**
     * Defines if the leadcard should be entered.
     */
    public bool $LeadCard = false;

    /**
     * If ShowResults is "True" determines the maximum number of results that will be shown.
     */
    public int $MaximumResults = 0;

    /**
     * Defines if the players can make themselves know by entering their player number on the
     * Bridgemate.
     */
    public bool $MemberNumbers = false;

    /**
     * If "True" all players must have been identified by their player number.
     */
    public bool $MemberNumbersNoBlankEntry = false;

    /**
     * Defines if the Bridgemate should check the order of play.
     */
    public bool $BoardOrderVerification = false;

    /**
     * Currently not supported.
     */
    public bool $HandRecordValidation = false;

    /**
     * Defines if BCS should automatically shut down when all results are in.
     */
    public bool $AutoShutDownBPC = false;

    /**
     * The pincode that the TD must enter before accessing the TD menu on the Bridgemate. Must be four
     * digits.
     */
    public ?string $BM2PINcode = null;

    /**
     * Defines if the TD must confirm No Play on the Bridgemate.
     */
    public bool $BM2ConfirmNP = false;

    /**
     * Defines if the Bridgemate should show how many boards in the round are left to play.
     */
    public bool $BM2RemainingBoards = false;

    /**
     * Defines if the Bridgemate should show the seatings for the next round.
     */
    public bool $BM2NextSeatings = false;

    /**
     * Defines if the Bridgemate can show the scores obtained during the round when a player presses
     * the appropriate button on the Bridgemate.
     */
    public bool $BM2ScoreRecap = false;

    /**
     * Defines if the Bridgemate should show the score recap wihtout promptimg after the last board of
     * the round has been played..
     */
    public bool $BM2AutoShowScoreRecap = false;

    /**
     * Defines if the players can correct scores themselves. If not the TD must be called to the table
     * to do this.
     */
    public bool $BM2ScoreCorrection = false;

    /**
     * Defines if the Brigemate should enter the board number automatically..
     */
    public bool $BM2AutoBoardNumber = false;

    /**
     * If BM2AutoBoardNumber is "True" defines if the boardnumber of the first board should be entered
     * manually. The subsequent boards will be filled in automatically.
     */
    public bool $BM2FirstBoardManually = false;

    /**
     * Determines if the entry of the leadcard should be checked against the handrecord.
     */
    public bool $BM2ValidateLeadCard = false;

    /**
     * Determines how the results overview will be formatted on the display.
     */
    public Bm2ResultsOverviewOption $BM2ResultsOverview = Bm2ResultsOverviewOption::FrequencyList6lines1column;

    /**
     * Determines if the Bridgemate shows the names of the players and if so at the start of each round
     * or in the first round only.
     */
    public Bm2ShowPlayerNamesOption $BM2ShowPlayerNames = Bm2ShowPlayerNamesOption::DoNotShow;

    /**
     * Determines if the Bridgemate should show the ranking and if so after play of the last board of a
     * round or after play of the last board of the session..
     */
    public Bm2ShowRankingOption $BM2Ranking = Bm2ShowRankingOption::DoNotShow;

    /**
     * Enable/disable the summary after end of session. (Enabled requires BM2Ranking=1 or 2
     */
    public bool $BM2GameSummary = false;

    /**
     * Defines if matchpoints or the percentage should be shown in the game summary.
     */
    public Bm2SummaryPointOption $BM2SummaryPoints = Bm2SummaryPointOption::Matchpoints;

    /**
     * Defines if the players can or must enter the pair number when entering the declaring side for a
     * contract. Enforcing this helps in detecting switched seatings.
     */
    public Bm2PairNumberEntryOption $BM2PairNumberEntry = Bm2PairNumberEntryOption::NoEntry;

    /**
     * Determines if the "Reset" key is available to the players, rather than to the TD only.
     */
    public bool $BM2ResetFunctionKey = false;

    /**
     * Currently not supported.
     */
    public bool $BM2RecordBidding = false;

    /**
     * Currently not supported.
     */
    public bool $BM2RecordPlay = false;

    /**
     * Currently not supported.
     */
    public bool $BM2ValidateRecording = false;

    /**
     * Currently not suppoorted.
     */
    public bool $BM2ShowHands = false;

    /**
     * Currently not supported
     */
    public Bm2NumberValidationOption $NumberValidation = Bm2NumberValidationOption::NoValidation;

    /**
     * Defines if the players must enter their player number each round.
     */
    public bool $BM2NumberEntryEachRound = false;

    /**
     * Currently not supported.
     */
    public bool $BM2NumberEntryPreloadValues = false;

    /**
     * Currently not supported.
     */
    public Bm2NameSource $BM2NameSource = Bm2NameSource::PlayerNamesTable;

    /**
     * Determines if the players can see the handrecord of the board they just played.
     */
    public bool $BM2ViewHandRecord = false;

    /**
     * Determines if the players can enter the handrecord for boards they played if not present.
     */
    public bool $BM2EnterHandRecord = false;

    /**
     * If BM2EnterHandRecord is "True" determines if the players can enter the handrecord after play of
     * the board or after playing all boards for the round.
     */
    public Bm2EnterHandrecordWhenOption $BM2EnterHandRecordWhen = Bm2EnterHandrecordWhenOption::AtEndOfRound;

    /**
     * Currently not supported.
     */
    public bool $BM2TextBasedNumber = false;

    /**
     * Defines if the "Call TD" button is visible on the Bridgemate.
     */
    public bool $BM2TDCall = false;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'ValidationMessages' => $this->ValidationMessages,
            'ShowResults' => $this->ShowResults,
            'ShowOwnResult' => $this->ShowOwnResult,
            'RepeatResults' => $this->RepeatResults,
            'ShowPercentage' => $this->ShowPercentage,
            'GroupSections' => $this->GroupSections,
            'ScorePoints' => $this->ScorePoints,
            'EnterResultsMethod' => $this->EnterResultsMethod,
            'ShowPairNumbers' => $this->ShowPairNumbers,
            'IntermediateResults' => $this->IntermediateResults,
            'AutopoweroffTime' => $this->AutopoweroffTime,
            'VerificationTime' => $this->VerificationTime,
            'ShowContract' => $this->ShowContract,
            'LeadCard' => $this->LeadCard,
            'MaximumResults' => $this->MaximumResults,
            'MemberNumbers' => $this->MemberNumbers,
            'MemberNumbersNoBlankEntry' => $this->MemberNumbersNoBlankEntry,
            'BoardOrderVerification' => $this->BoardOrderVerification,
            'HandRecordValidation' => $this->HandRecordValidation,
            'AutoShutDownBPC' => $this->AutoShutDownBPC,
            'BM2PINcode' => $this->BM2PINcode,
            'BM2ConfirmNP' => $this->BM2ConfirmNP,
            'BM2RemainingBoards' => $this->BM2RemainingBoards,
            'BM2NextSeatings' => $this->BM2NextSeatings,
            'BM2ScoreRecap' => $this->BM2ScoreRecap,
            'BM2AutoShowScoreRecap' => $this->BM2AutoShowScoreRecap,
            'BM2ScoreCorrection' => $this->BM2ScoreCorrection,
            'BM2AutoBoardNumber' => $this->BM2AutoBoardNumber,
            'BM2FirstBoardManually' => $this->BM2FirstBoardManually,
            'BM2ValidateLeadCard' => $this->BM2ValidateLeadCard,
            'BM2ResultsOverview' => $this->BM2ResultsOverview,
            'BM2ShowPlayerNames' => $this->BM2ShowPlayerNames,
            'BM2Ranking' => $this->BM2Ranking,
            'BM2GameSummary' => $this->BM2GameSummary,
            'BM2SummaryPoints' => $this->BM2SummaryPoints,
            'BM2PairNumberEntry' => $this->BM2PairNumberEntry,
            'BM2ResetFunctionKey' => $this->BM2ResetFunctionKey,
            'BM2RecordBidding' => $this->BM2RecordBidding,
            'BM2RecordPlay' => $this->BM2RecordPlay,
            'BM2ValidateRecording' => $this->BM2ValidateRecording,
            'BM2ShowHands' => $this->BM2ShowHands,
            'NumberValidation' => $this->NumberValidation,
            'BM2NumberEntryEachRound' => $this->BM2NumberEntryEachRound,
            'BM2NumberEntryPreloadValues' => $this->BM2NumberEntryPreloadValues,
            'BM2NameSource' => $this->BM2NameSource,
            'BM2ViewHandRecord' => $this->BM2ViewHandRecord,
            'BM2EnterHandRecord' => $this->BM2EnterHandRecord,
            'BM2EnterHandRecordWhen' => $this->BM2EnterHandRecordWhen,
            'BM2TextBasedNumber' => $this->BM2TextBasedNumber,
            'BM2TDCall' => $this->BM2TDCall,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        $dto->ShowResults = $data['ShowResults'] ?? false;
        $dto->ShowOwnResult = $data['ShowOwnResult'] ?? false;
        $dto->RepeatResults = $data['RepeatResults'] ?? false;
        $dto->ShowPercentage = $data['ShowPercentage'] ?? false;
        $dto->GroupSections = $data['GroupSections'] ?? false;
        $dto->ScorePoints = Bm2PointScorePerspectiveOption::tryFrom($data['ScorePoints'] ?? 0) ?? Bm2PointScorePerspectiveOption::FromNorthSouth;
        $dto->EnterResultsMethod = BM2ResultEntryMethod::tryFrom($data['EnterResultsMethod'] ?? 0) ?? BM2ResultEntryMethod::UpDownTricks;
        $dto->ShowPairNumbers = $data['ShowPairNumbers'] ?? false;
        $dto->IntermediateResults = $data['IntermediateResults'] ?? false;
        $dto->AutopoweroffTime = $data['AutopoweroffTime'] ?? 0;
        $dto->VerificationTime = $data['VerificationTime'] ?? 0;
        $dto->ShowContract = Bm2ContractRepresentationOption::tryFrom($data['ShowContract'] ?? 0) ?? Bm2ContractRepresentationOption::UseSymbols;
        $dto->LeadCard = $data['LeadCard'] ?? false;
        $dto->MaximumResults = $data['MaximumResults'] ?? 0;
        $dto->MemberNumbers = $data['MemberNumbers'] ?? false;
        $dto->MemberNumbersNoBlankEntry = $data['MemberNumbersNoBlankEntry'] ?? false;
        $dto->BoardOrderVerification = $data['BoardOrderVerification'] ?? false;
        $dto->HandRecordValidation = $data['HandRecordValidation'] ?? false;
        $dto->AutoShutDownBPC = $data['AutoShutDownBPC'] ?? false;
        $dto->BM2PINcode = $data['BM2PINcode'] ?? null;
        $dto->BM2ConfirmNP = $data['BM2ConfirmNP'] ?? false;
        $dto->BM2RemainingBoards = $data['BM2RemainingBoards'] ?? false;
        $dto->BM2NextSeatings = $data['BM2NextSeatings'] ?? false;
        $dto->BM2ScoreRecap = $data['BM2ScoreRecap'] ?? false;
        $dto->BM2AutoShowScoreRecap = $data['BM2AutoShowScoreRecap'] ?? false;
        $dto->BM2ScoreCorrection = $data['BM2ScoreCorrection'] ?? false;
        $dto->BM2AutoBoardNumber = $data['BM2AutoBoardNumber'] ?? false;
        $dto->BM2FirstBoardManually = $data['BM2FirstBoardManually'] ?? false;
        $dto->BM2ValidateLeadCard = $data['BM2ValidateLeadCard'] ?? false;
        $dto->BM2ResultsOverview = Bm2ResultsOverviewOption::tryFrom($data['BM2ResultsOverview'] ?? 0) ?? Bm2ResultsOverviewOption::FrequencyList6lines1column;
        $dto->BM2ShowPlayerNames = Bm2ShowPlayerNamesOption::tryFrom($data['BM2ShowPlayerNames'] ?? 0) ?? Bm2ShowPlayerNamesOption::DoNotShow;
        $dto->BM2Ranking = Bm2ShowRankingOption::tryFrom($data['BM2Ranking'] ?? 0) ?? Bm2ShowRankingOption::DoNotShow;
        $dto->BM2GameSummary = $data['BM2GameSummary'] ?? false;
        $dto->BM2SummaryPoints = Bm2SummaryPointOption::tryFrom($data['BM2SummaryPoints'] ?? 0) ?? Bm2SummaryPointOption::Matchpoints;
        $dto->BM2PairNumberEntry = Bm2PairNumberEntryOption::tryFrom($data['BM2PairNumberEntry'] ?? 0) ?? Bm2PairNumberEntryOption::NoEntry;
        $dto->BM2ResetFunctionKey = $data['BM2ResetFunctionKey'] ?? false;
        $dto->BM2RecordBidding = $data['BM2RecordBidding'] ?? false;
        $dto->BM2RecordPlay = $data['BM2RecordPlay'] ?? false;
        $dto->BM2ValidateRecording = $data['BM2ValidateRecording'] ?? false;
        $dto->BM2ShowHands = $data['BM2ShowHands'] ?? false;
        $dto->NumberValidation = Bm2NumberValidationOption::tryFrom($data['NumberValidation'] ?? 0) ?? Bm2NumberValidationOption::NoValidation;
        $dto->BM2NumberEntryEachRound = $data['BM2NumberEntryEachRound'] ?? false;
        $dto->BM2NumberEntryPreloadValues = $data['BM2NumberEntryPreloadValues'] ?? false;
        $dto->BM2NameSource = Bm2NameSource::tryFrom($data['BM2NameSource'] ?? 0) ?? Bm2NameSource::PlayerNamesTable;
        $dto->BM2ViewHandRecord = $data['BM2ViewHandRecord'] ?? false;
        $dto->BM2EnterHandRecord = $data['BM2EnterHandRecord'] ?? false;
        $dto->BM2EnterHandRecordWhen = Bm2EnterHandrecordWhenOption::tryFrom($data['BM2EnterHandRecordWhen'] ?? 0) ?? Bm2EnterHandrecordWhenOption::AtEndOfRound;
        $dto->BM2TextBasedNumber = $data['BM2TextBasedNumber'] ?? false;
        $dto->BM2TDCall = $data['BM2TDCall'] ?? false;
        return $dto;
    }
}
