<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Instructs BCS to continue working with a previously created event using the
 * ScoringProgramPipeClient.Continue method or the ScoringProgramPipeClient.ContinueAsync method.
 */
class ContinueDTO implements \JsonSerializable
{
    /**
     * Tells BCS which event to continue. When there is only one session the event guid will be its
     * session guid unless it was set to a different value in the original InitDTO.
     */
    public ?string $EventGuid = null;

    /**
     * Required when using the http interface for the dataconnector
     */
    public ?string $ClubId = null;

    /**
     * 1: Just start BCS and let it reconnect to the last used scoring file if it contains a session
     * with the correct guid. 5: Start BCS, let it reconnect and start reading. add 128: clear all
     * previous data from the Data Connector.
     */
    public int $Commands = 0;

    /**
     * Optional. Specifies a different directory for the BCS scoring file. Only use in advanced
     * scenarios. If used make sure that the directory exists.
     */
    public ?string $AlternativeDataFolder = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'EventGuid' => $this->EventGuid,
            'ClubId' => $this->ClubId,
            'Commands' => $this->Commands,
            'AlternativeDataFolder' => $this->AlternativeDataFolder,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->EventGuid = $data['EventGuid'] ?? null;
        $dto->ClubId = $data['ClubId'] ?? null;
        $dto->Commands = $data['Commands'] ?? 0;
        $dto->AlternativeDataFolder = $data['AlternativeDataFolder'] ?? null;
        return $dto;
    }
}
