<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies the data type that the ScoringProgramResponse's SerializedData property should contain.
 */
enum DataConnectorResponseData: int
{
    /**
     * There is no accompanying data.
     */
    case None = 0;
    /**
     * Acknowledges a command that does not return data
     */
    case OK = 1;
    /**
     * Not in use.
     */
    case Paused = 2;
    /**
     * Signals a non essential error.
     */
    case Warning = 3;
    /**
     * Signals that an error occurred. The accompanying data will be a serialized string explaining the
     * error.
     */
    case Error = 4;
    /**
     * Data to create a new event. An InitDTO.
     */
    case InitData = 5;
    /**
     * Data to continue a previously created event. A ContinueDTO.
     */
    case ContinueData = 6;
    /**
     * Data to update sections and their scoringgroups. A collection of ScoringGroupDTO.
     */
    case SectionData = 7;
    /**
     * Data to update the BM2 settings. A Bridgemate2SettingsDTO.
     */
    case Bridgemate2Settings = 8;
    /**
     * Data to update the BM3 settings. A Bridgemate2SettingsDTO.
     */
    case Bridgemate3Settings = 9;
    /**
     * First name, last name, country code for players. A PlayerDataDTO.
     */
    case PlayerData = 10;
    /**
     * Position of players at a table in a round. A ParticipationDTO.
     */
    case Participations = 11;
    /**
     * Boardresults. A collection of ResultDTO.
     */
    case Results = 12;
    /**
     * Handrecords. A collection of HandrecordDTO.
     */
    case Handrecords = 13;
    /**
     * Data to update the movement for a section. A SectionDTO.
     */
    case Movement = 14;
    /**
     * Data for a new session. A SectionDTO.
     */
    case Session = 15;
    /**
     * Sessions, their scoringroups and their sections. A BCSManagementResponseDTO with an array of
     * SessionInfoDTOs as its SessionInformation property.
     */
    case Sessions = 16;
    /**
     * Guid-name pairs of the sessions currently being administered. Embedded in a
     * BCSManagementResponseDTO.
     */
    case EventInfo = 17;
    /**
     * Guid-name-scoringfile location for all sessions that are present in BCS' data. Embedded in a
     * BCSManagementResponseDTO.
     */
    case AllSessionsInfo = 18;
    /**
     * The location of the scoring file for BCS. Embedded in a BCSManagementResponseDTO.
     */
    case ScoringFileLocation = 19;
    /**
     * The data is a shutdown request. Embedded in a BCSManagementRequesetDTO.
     */
    case ShutDownRequest = 20;
    /**
     * A collection of td calls. TdCallDTO/>
     */
    case TdCalls = 21;
    /**
     * Currently not supported.
     */
    case TestData = 22;
}
