<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Clarifies what type of error occurred, causing the ScoringProgramRequest to fail.
 */
enum ErrorType: int
{
    /**
     * The is no error.
     */
    case None = 0;
    /**
     * The Data Connector was handling an other request.
     */
    case Busy = 1;
    /**
     * The sent data was null or did not contain any elements while the request command should come
     * with data.
     */
    case NoData = 2;
    /**
     * Signals that sent data that meant to update exisiting data already existed.
     */
    case NoUpdates = 3;
    /**
     * The sent data did not comply to a known round on a table.
     */
    case Movement = 4;
    /**
     * The dto has invalid data.
     */
    case Validation = 5;
    /**
     * No record for the given primary key was found.
     */
    case EntryUnknown = 6;
    /**
     * An error occurred when processing the data.
     */
    case Exception = 7;
    /**
     * The requested operation is currently not supported.
     */
    case NotImplemented = 8;
    /**
     * A meaningful response to the request was exptected, but an empty response came back.
     */
    case EmptyResponse = 9;
    /**
     * The connection to the Data Connector is broken.
     */
    case NoConnection = 10;
    /**
     * The operation was blocked by a previous long running operation.
     */
    case TimeOut = 11;
    /**
     * The datatype of the dtos did not conform to the request command.
     */
    case WrongDataType = 12;
    /**
     * The response command did not conform to the request command.
     */
    case UnexpectedCommand = 13;
    /**
     * Unknown error.
     */
    case Unknown = 14;
}
