<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Contains the data for a handrecord and optionally its double dummy values.
 */
class HandrecordDTO implements \JsonSerializable
{
    /**
     * Required. The guid of the session the handrecord belongs to. A string built from a Guid, without
     * the curly braces or connecting dashes. The letters must be capitals. Must be unique
     */
    public ?string $SessionGuid = null;

    /**
     * Required. The number of the scoringgroup that the handrecord belongs to.
     */
    public int $ScoringGroupNumber = 0;

    /**
     * Required, any of the sections that are part of the scoringgroup.
     */
    public ?string $SectionLetters = null;

    /**
     * Required. Must be greater than zero.
     */
    public int $BoardNumber = 0;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $NorthClubs = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $NorthDiamonds = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $NorthHearts = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $NorthSpades = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $EastClubs = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $EastDiamonds = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $EastHearts = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $EastSpades = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $SouthClubs = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $SouthDiamonds = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $SouthHearts = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $SouthSpades = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $WestClubs = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $WestDiamonds = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $WestHearts = null;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    public ?string $WestSpades = null;

    /**
     * It "True" the double dummy values will be processed by the Data Connector.
     */
    public bool $HasHandEvaluationData = false;

    /**
     * The number of tricks that can be made with North as declarer and Clubs as denomination.
     */
    public int $DoubleDummyNorthClubs = 0;

    /**
     * The number of tricks that can be made with North as declarer and Diamonds as denomination.
     */
    public int $DoubleDummyNorthDiamonds = 0;

    /**
     * The number of tricks that can be made with North as declarer and Hearts as denomination.
     */
    public int $DoubleDummyNorthHearts = 0;

    /**
     * The number of tricks that can be made with North as declarer and Spades as denomination.
     */
    public int $DoubleDummyNorthSpades = 0;

    /**
     * The number of tricks that can be made with North as declarer and No Trump as denomination.
     */
    public int $DoubleDummyNorthNoTrump = 0;

    /**
     * The number of tricks that can be made with East as declarer and Clubs as denomination.
     */
    public int $DoubleDummyEastClubs = 0;

    /**
     * The number of tricks that can be made with East as declarer and Diamonds as denomination.
     */
    public int $DoubleDummyEastDiamonds = 0;

    /**
     * The number of tricks that can be made with East as declarer and Hearts as denomination.
     */
    public int $DoubleDummyEastHearts = 0;

    /**
     * The number of tricks that can be made with East as declarer and Spades as denomination.
     */
    public int $DoubleDummyEastSpades = 0;

    /**
     * The number of tricks that can be made with East as declarer and No Trump as denomination.
     */
    public int $DoubleDummyEastNoTrump = 0;

    /**
     * The number of tricks that can be made with South as declarer and Clubs as denomination.
     */
    public int $DoubleDummySouthClubs = 0;

    /**
     * The number of tricks that can be made with South as declarer and Diamonds as denomination.
     */
    public int $DoubleDummySouthDiamonds = 0;

    /**
     * The number of tricks that can be made with South as declarer and Hearts as denomination.
     */
    public int $DoubleDummySouthHearts = 0;

    /**
     * The number of tricks that can be made with South as declarer and Spades as denomination.
     */
    public int $DoubleDummySouthSpades = 0;

    /**
     * The number of tricks that can be made with South as declarer and No Trump as denomination.
     */
    public int $DoubleDummySouthNoTrump = 0;

    /**
     * The number of tricks that can be made with West as declarer and Clubs as denomination.
     */
    public int $DoubleDummyWestClubs = 0;

    /**
     * The number of tricks that can be made with West as declarer and Diamonds as denomination.
     */
    public int $DoubleDummyWestDiamonds = 0;

    /**
     * The number of tricks that can be made with West as declarer and Hearts as denomination.
     */
    public int $DoubleDummyWestHearts = 0;

    /**
     * The number of tricks that can be made with West as declarer and Spades as denomination.
     */
    public int $DoubleDummyWestSpades = 0;

    /**
     * The number of tricks that can be made with West as declarer and No Trump as denomination.
     */
    public int $DoubleDummyWestNoTrump = 0;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'ScoringGroupNumber' => $this->ScoringGroupNumber,
            'SectionLetters' => $this->SectionLetters,
            'BoardNumber' => $this->BoardNumber,
            'NorthClubs' => $this->NorthClubs,
            'NorthDiamonds' => $this->NorthDiamonds,
            'NorthHearts' => $this->NorthHearts,
            'NorthSpades' => $this->NorthSpades,
            'EastClubs' => $this->EastClubs,
            'EastDiamonds' => $this->EastDiamonds,
            'EastHearts' => $this->EastHearts,
            'EastSpades' => $this->EastSpades,
            'SouthClubs' => $this->SouthClubs,
            'SouthDiamonds' => $this->SouthDiamonds,
            'SouthHearts' => $this->SouthHearts,
            'SouthSpades' => $this->SouthSpades,
            'WestClubs' => $this->WestClubs,
            'WestDiamonds' => $this->WestDiamonds,
            'WestHearts' => $this->WestHearts,
            'WestSpades' => $this->WestSpades,
            'HasHandEvaluationData' => $this->HasHandEvaluationData,
            'DoubleDummyNorthClubs' => $this->DoubleDummyNorthClubs,
            'DoubleDummyNorthDiamonds' => $this->DoubleDummyNorthDiamonds,
            'DoubleDummyNorthHearts' => $this->DoubleDummyNorthHearts,
            'DoubleDummyNorthSpades' => $this->DoubleDummyNorthSpades,
            'DoubleDummyNorthNoTrump' => $this->DoubleDummyNorthNoTrump,
            'DoubleDummyEastClubs' => $this->DoubleDummyEastClubs,
            'DoubleDummyEastDiamonds' => $this->DoubleDummyEastDiamonds,
            'DoubleDummyEastHearts' => $this->DoubleDummyEastHearts,
            'DoubleDummyEastSpades' => $this->DoubleDummyEastSpades,
            'DoubleDummyEastNoTrump' => $this->DoubleDummyEastNoTrump,
            'DoubleDummySouthClubs' => $this->DoubleDummySouthClubs,
            'DoubleDummySouthDiamonds' => $this->DoubleDummySouthDiamonds,
            'DoubleDummySouthHearts' => $this->DoubleDummySouthHearts,
            'DoubleDummySouthSpades' => $this->DoubleDummySouthSpades,
            'DoubleDummySouthNoTrump' => $this->DoubleDummySouthNoTrump,
            'DoubleDummyWestClubs' => $this->DoubleDummyWestClubs,
            'DoubleDummyWestDiamonds' => $this->DoubleDummyWestDiamonds,
            'DoubleDummyWestHearts' => $this->DoubleDummyWestHearts,
            'DoubleDummyWestSpades' => $this->DoubleDummyWestSpades,
            'DoubleDummyWestNoTrump' => $this->DoubleDummyWestNoTrump,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->ScoringGroupNumber = $data['ScoringGroupNumber'] ?? 0;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->BoardNumber = $data['BoardNumber'] ?? 0;
        $dto->NorthClubs = $data['NorthClubs'] ?? null;
        $dto->NorthDiamonds = $data['NorthDiamonds'] ?? null;
        $dto->NorthHearts = $data['NorthHearts'] ?? null;
        $dto->NorthSpades = $data['NorthSpades'] ?? null;
        $dto->EastClubs = $data['EastClubs'] ?? null;
        $dto->EastDiamonds = $data['EastDiamonds'] ?? null;
        $dto->EastHearts = $data['EastHearts'] ?? null;
        $dto->EastSpades = $data['EastSpades'] ?? null;
        $dto->SouthClubs = $data['SouthClubs'] ?? null;
        $dto->SouthDiamonds = $data['SouthDiamonds'] ?? null;
        $dto->SouthHearts = $data['SouthHearts'] ?? null;
        $dto->SouthSpades = $data['SouthSpades'] ?? null;
        $dto->WestClubs = $data['WestClubs'] ?? null;
        $dto->WestDiamonds = $data['WestDiamonds'] ?? null;
        $dto->WestHearts = $data['WestHearts'] ?? null;
        $dto->WestSpades = $data['WestSpades'] ?? null;
        $dto->HasHandEvaluationData = $data['HasHandEvaluationData'] ?? false;
        $dto->DoubleDummyNorthClubs = $data['DoubleDummyNorthClubs'] ?? 0;
        $dto->DoubleDummyNorthDiamonds = $data['DoubleDummyNorthDiamonds'] ?? 0;
        $dto->DoubleDummyNorthHearts = $data['DoubleDummyNorthHearts'] ?? 0;
        $dto->DoubleDummyNorthSpades = $data['DoubleDummyNorthSpades'] ?? 0;
        $dto->DoubleDummyNorthNoTrump = $data['DoubleDummyNorthNoTrump'] ?? 0;
        $dto->DoubleDummyEastClubs = $data['DoubleDummyEastClubs'] ?? 0;
        $dto->DoubleDummyEastDiamonds = $data['DoubleDummyEastDiamonds'] ?? 0;
        $dto->DoubleDummyEastHearts = $data['DoubleDummyEastHearts'] ?? 0;
        $dto->DoubleDummyEastSpades = $data['DoubleDummyEastSpades'] ?? 0;
        $dto->DoubleDummyEastNoTrump = $data['DoubleDummyEastNoTrump'] ?? 0;
        $dto->DoubleDummySouthClubs = $data['DoubleDummySouthClubs'] ?? 0;
        $dto->DoubleDummySouthDiamonds = $data['DoubleDummySouthDiamonds'] ?? 0;
        $dto->DoubleDummySouthHearts = $data['DoubleDummySouthHearts'] ?? 0;
        $dto->DoubleDummySouthSpades = $data['DoubleDummySouthSpades'] ?? 0;
        $dto->DoubleDummySouthNoTrump = $data['DoubleDummySouthNoTrump'] ?? 0;
        $dto->DoubleDummyWestClubs = $data['DoubleDummyWestClubs'] ?? 0;
        $dto->DoubleDummyWestDiamonds = $data['DoubleDummyWestDiamonds'] ?? 0;
        $dto->DoubleDummyWestHearts = $data['DoubleDummyWestHearts'] ?? 0;
        $dto->DoubleDummyWestSpades = $data['DoubleDummyWestSpades'] ?? 0;
        $dto->DoubleDummyWestNoTrump = $data['DoubleDummyWestNoTrump'] ?? 0;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
