<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Contains information on how to construct a new event, with its sessions, sections, tables and
 * rounds. Optionally player data, participations and handrecords can be added. Doing this is more
 * performant than adding them later. Is used as a parameter for the
 * ScoringProgramPipeClient.Initialize or the ScoringProgramPipeClient.InitializeAsync method.
 */
class InitDTO implements \JsonSerializable
{
    /**
     * Instructs the Data Connector to start BCS.
     */
    public const StartBCS = 1;

    /**
     * Instructs BCS to create a new event from the data in this DTO.
     */
    public const Command_Reset = 2;

    /**
     * Instructs BCS to start reading from the Data Connector.
     */
    public const Command_StartReading = 4;

    /**
     * Instructs BCS to upload the sessions to the Bridgemate App server.
     */
    public const Command_ShowInApp = 8;

    /**
     * Instructs BCS to start minimized.
     */
    public const Command_Minimize = 16;

    /**
     * Instructs BCS to shut down after the last result has been processed.
     */
    public const Command_AutoShutDownBPC = 32;

    /**
     * Sets the log level to "Debug" rather than "Info".
     */
    public const Command_LogLevel_Debug = 64;

    /**
     * Instructs the Data Connector to clear all its previous data and start with a clean slate.
     */
    public const Command_ClearData = 128;

    /**
     * Instructs the Data Connector to use communicate over http.
     */
    public const Command_UseHttp = 256;

    /**
     * Instructions to BCS. Add up the values to combine. 1. Start BCS (if not already started). 2:
     * Reset the Bridgemates (and App) and fill them with the provided data. 4: Start Reading from the
     * Bridgemates, Data Connector (and App). 8: Upload the sessions to the app. 16: Minimize BCS
     * 32:Close BCS when all results have been processed. 64: Lower the logging level from "Info" to
     * "Debug". 128:Clear all previous data from the Data Connector queue.
     */
    public int $Commands = 0;

    /**
     * Required if the number of sessions is greater than one. This signals that BCS should administer
     * these sessions together.
     */
    public ?string $EventGuid = null;

    /**
     * Required when using http for communication with the data connector.
     */
    public ?string $ClubId = null;

    /**
     * Optional. Specifies a different directory for the BCS scoring file. Only use in advanced
     * scenarios. If used make sure that the directory exists.
     */
    public ?string $AlternativeDataFolder = null;

    /**
     * Required, must be at least one.
     * @var SessionDTO[]|null
     */
    public ?array $Sessions = null;

    /**
     * Optional: the data of at least the players that will participate in the sessions. Player data is
     * required for every participation that has its a SessionGuid and PlayerNumber properties set.
     * @var PlayerDataDTO[]|null
     */
    public ?array $PlayerData = null;

    /**
     * Optional. Each participation with its SessionGuid and PlayerNumber properties set must have a
     * corresponding player data element that specifies at least its name.
     * @var ParticipationDTO[]|null
     */
    public ?array $Participations = null;

    /**
     * Optional. The handrecords for each session.
     * @var HandrecordDTO[]|null
     */
    public ?array $Handrecords = null;

    /**
     * Optional. The settings for the Bridgemate 2 for all sections (if in use).
     * @var Bridgemate2SettingsDTO[]|null
     */
    public ?array $Bridgemate2Settings = null;

    /**
     * Optional. The settings for the Bridgemate 3 for all sections (if in use).
     * @var Bridgemate3SettingsDTO[]|null
     */
    public ?array $Bridgemate3Settings = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'Commands' => $this->Commands,
            'EventGuid' => $this->EventGuid,
            'ClubId' => $this->ClubId,
            'AlternativeDataFolder' => $this->AlternativeDataFolder,
            'Sessions' => $this->Sessions,
            'PlayerData' => $this->PlayerData,
            'Participations' => $this->Participations,
            'Handrecords' => $this->Handrecords,
            'Bridgemate2Settings' => $this->Bridgemate2Settings,
            'Bridgemate3Settings' => $this->Bridgemate3Settings,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->Commands = $data['Commands'] ?? 0;
        $dto->EventGuid = $data['EventGuid'] ?? null;
        $dto->ClubId = $data['ClubId'] ?? null;
        $dto->AlternativeDataFolder = $data['AlternativeDataFolder'] ?? null;
        $dto->Sessions = isset($data['Sessions']) ? array_map(static fn (array $item): SessionDTO => SessionDTO::fromArray($item), $data['Sessions']) : null;
        $dto->PlayerData = isset($data['PlayerData']) ? array_map(static fn (array $item): PlayerDataDTO => PlayerDataDTO::fromArray($item), $data['PlayerData']) : null;
        $dto->Participations = isset($data['Participations']) ? array_map(static fn (array $item): ParticipationDTO => ParticipationDTO::fromArray($item), $data['Participations']) : null;
        $dto->Handrecords = isset($data['Handrecords']) ? array_map(static fn (array $item): HandrecordDTO => HandrecordDTO::fromArray($item), $data['Handrecords']) : null;
        $dto->Bridgemate2Settings = isset($data['Bridgemate2Settings']) ? array_map(static fn (array $item): Bridgemate2SettingsDTO => Bridgemate2SettingsDTO::fromArray($item), $data['Bridgemate2Settings']) : null;
        $dto->Bridgemate3Settings = isset($data['Bridgemate3Settings']) ? array_map(static fn (array $item): Bridgemate3SettingsDTO => Bridgemate3SettingsDTO::fromArray($item), $data['Bridgemate3Settings']) : null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
