<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1040.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * This class can be used: 1. To give names for the players in the first round by only specifying their
 * player numbers. For this to work the names belonging to the playernumber must have been passed first
 * using PlayerDTO's. 2. To give names for the players in the first round by omitting their
 * playernumber. In this case the players will be registerd for this session only. 3. To specify the
 * seating for every round explicitly, one DTO per (table, round, position). This requires the section
 * to have been created with HasExplicitParticipations set to true. BCS then stores each participation
 * for its own round exactly as sent and does not calculate seatings from the movement. Use this for
 * individual sessions and other formats where partnerships change between rounds. 4. To report that a
 * seat was emptied (IsRemoval): the player who sat there was removed. Such a DTO carries no player
 * number and no name. The combination of both playernumber and name details is not supported.
 */
class ParticipationDTO implements \JsonSerializable
{
    /**
     * Required. The guid of the session the participation belongs to. A string built from a Guid,
     * without the curly braces or connecting dashes. The letters must be capitals
     */
    public ?string $SessionGuid = null;

    /**
     * Required. The letters of the section the participation belongs to. Can be A-Z, AA, BB, CC,...ZZ,
     * AAA, BBB, CCC, ... ZZZ
     */
    public ?string $SectionLetters = null;

    /**
     * Required. The number of the table for the player in the round.
     */
    public int $TableNumber = 0;

    /**
     * Required. The position on the table for the player in the round. 1: North 2: East 3: South 4:
     * West
     */
    public TableDirection $Direction = TableDirection::None;

    /**
     * Optional. The round the participation applies to. The values zero and one are equivalent: they
     * denote the table where the player sits in the first round, and BCS will use the known movement
     * to calculate the player's positions in the other rounds. Values higher than one are only valid
     * for sections that were created with HasExplicitParticipations set to true. For such sections BCS
     * stores every participation for its own round exactly as sent and performs no movement-based
     * calculation. Sending a round number higher than one for any other section is a validation error.
     */
    public int $RoundNumber = 0;

    /**
     * Optional, but must be present together with the SessionGuid if no name details are passed. The
     * playernumber must have been passed beforehand using a PlayerDTO containg the name details.
     */
    public ?string $PlayerNumber = null;

    /**
     * Signals that this player was swapped with his partner: North was swapped with South, or East
     * with West.
     */
    public bool $IsPlayerSwap = false;

    /**
     * Signals that the player who sat at this seat was removed and the seat is now empty. The DTO then
     * carries no player: PlayerNumber, FirstName, LastName and CountryCode must be empty. The seat is
     * identified by the session, section, table, direction and round, with the same rules as any
     * participation: round zero or one means the first round, in a section without explicit
     * participations the player leaves the pair (every round), in a section with explicit
     * participations only the given round is emptied.
     */
    public bool $IsRemoval = false;

    /**
     * Optional, must only be used when the playernumber is empty.
     */
    public ?string $FirstName = null;

    /**
     * Required when the playernumber is empty.Must only be used when the playernumber is empty.
     */
    public ?string $LastName = null;

    /**
     * Optional, must only be used when the playernumber is empty.
     */
    public ?string $CountryCode = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'TableNumber' => $this->TableNumber,
            'Direction' => $this->Direction,
            'RoundNumber' => $this->RoundNumber,
            'PlayerNumber' => $this->PlayerNumber,
            'IsPlayerSwap' => $this->IsPlayerSwap,
            'IsRemoval' => $this->IsRemoval,
            'FirstName' => $this->FirstName,
            'LastName' => $this->LastName,
            'CountryCode' => $this->CountryCode,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->TableNumber = $data['TableNumber'] ?? 0;
        $dto->Direction = TableDirection::tryFrom($data['Direction'] ?? 0) ?? TableDirection::None;
        $dto->RoundNumber = $data['RoundNumber'] ?? 0;
        $dto->PlayerNumber = $data['PlayerNumber'] ?? null;
        $dto->IsPlayerSwap = $data['IsPlayerSwap'] ?? false;
        $dto->IsRemoval = $data['IsRemoval'] ?? false;
        $dto->FirstName = $data['FirstName'] ?? null;
        $dto->LastName = $data['LastName'] ?? null;
        $dto->CountryCode = $data['CountryCode'] ?? null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
