<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * This class carries information on a player: name, country and playernumber. Each ParticipationDTO
 * carrying a non empty playernumber property must have a corresponding PlayerDataDTO woith the given
 * playernumber (and SessionGuid) that was sent before the ParticipationDTO was sent.
 */
class PlayerDataDTO implements \JsonSerializable
{
    /**
     * Required, the guid of the session the player participates in.
     */
    public ?string $SessionGuid = null;

    /**
     * Required when using the http interface for the dataconnector
     */
    public ?string $ClubId = null;

    /**
     * Required, must uniquely identify the player within the session.
     */
    public ?string $PlayerNumber = null;

    /**
     * Optional
     */
    public ?string $FirstName = null;

    /**
     * Required
     */
    public ?string $LastName = null;

    /**
     * Optional
     */
    public ?string $CountryCode = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'ClubId' => $this->ClubId,
            'PlayerNumber' => $this->PlayerNumber,
            'FirstName' => $this->FirstName,
            'LastName' => $this->LastName,
            'CountryCode' => $this->CountryCode,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->ClubId = $data['ClubId'] ?? null;
        $dto->PlayerNumber = $data['PlayerNumber'] ?? null;
        $dto->FirstName = $data['FirstName'] ?? null;
        $dto->LastName = $data['LastName'] ?? null;
        $dto->CountryCode = $data['CountryCode'] ?? null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
