<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * This class carries information on the result of a board that was played in a specific round on a
 * specific table. The Level property is also used to express "No Play" and artificial results (using
 * negative values).
 */
class ResultDTO implements \JsonSerializable
{
    /**
     * The result pertains to North-South only. i.e.: The East-West pair may have a different result
     * and a ResultDTO with its ScoringDirection property set to ScoringDirection_EW must be provided.
     */
    public const ScoringDirection_NS = 1;

    /**
     * The result pertains to East-West only. i.e.: The North-South pair may have a different result
     * and a ResultDTO with its ScoringDirection property set to ScoringDirection_NS must be provided.
     */
    public const ScoringDirection_EW = 2;

    /**
     * The result pertains to both North-South and East-West.
     */
    public const ScoringDirection_NSEW = 3;

    /**
     * The denomination of the contract is Clubs.
     */
    public const Denomination_Clubs = 1;

    /**
     * The denomination of the contract is Diamonds.
     */
    public const Denomination_Diamonds = 2;

    /**
     * The denomination of the contract is Hearts.
     */
    public const Denomination_Hearts = 3;

    /**
     * The denomination of the contract is Spades.
     */
    public const Denomination_Spades = 4;

    /**
     * The denomination of the contract is No Trump.
     */
    public const Denomination_NoTrump = 5;

    /**
     * Declarer is the player on the North seat.
     */
    public const Direction_North = 1;

    /**
     * Declarer is the player on the East seat.
     */
    public const Direction_East = 2;

    /**
     * Declarer is the player on the South seat.
     */
    public const Direction_South = 3;

    /**
     * Declarer is the player on the West seat.
     */
    public const Direction_West = 4;

    /**
     * The contract of the board was "Pass".
     */
    public const ContractLevel_Pass = 0;

    /**
     * The board was not played.
     */
    public const ContractLevel_NoPLay = -10;

    /**
     * The contract was not doubled or redoubled.
     */
    public const Stake_Normal = 0;

    /**
     * The contract was doubled.
     */
    public const Stake_Doubled = 1;

    /**
     * The contract was redoubled.
     */
    public const Stake_Redoubled = 2;

    /**
     * An artificial score of Average Minus for the North-South pair and Average Minus for the
     * East-West pair if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW.
     * If the ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public const AvgMinMin = -1;

    /**
     * An artificial score of Average Minus for the North-South pair and Average for the East-West
     * pair.
     */
    public const AvgMinAvg = -2;

    /**
     * An artificial score of Average Minus for the North-South pair and Average Plus for the East-West
     * pair if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public const AvgMinPlus = -3;

    /**
     * An artificial score of Average for the North-South pair and Average Minus for the East-West pair
     * if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public const AvgAvgMin = -4;

    /**
     * An artificial score of Average for the North-South pair and Average for the East-West pair.
     */
    public const AvgAvgAvg = -5;

    /**
     * An artificial score of Average for the North-South pair and Average Plus for the East-West pair
     * if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public const AvgAvgPlus = -6;

    /**
     * An artificial score of Average Plus for the North-South pair and Average Minus for the East-West
     * pair if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public const AvgPlusMin = -7;

    /**
     * An artificial score of Average Plus for the North-South pair and Average for the East-West pair
     * if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public const AvgPlusAvg = -8;

    /**
     * An artificial score of Average Plus for the North-South pair and Average Plus for the East-West
     * pair.
     */
    public const AvgPlusPlus = -9;

    /**
     * Required.The guid of the session the result belongs to.
     */
    public ?string $SessionGuid = null;

    /**
     * Required, the letters of the section in which the result was obtained. The section must exist.
     */
    public ?string $SectionLetters = null;

    /**
     * Required, must be greater than zero. The table must exist.
     */
    public int $TableNumber = 0;

    /**
     * Required, must be greater than zero. The round must exist.
     */
    public int $RoundNumber = 0;

    /**
     * Required, must be greater than zero. The board must exist, i.e.: it must have been specified in
     * the RoundDTO's LowBoardNumber and HighBoardNumber properties.
     */
    public int $BoardNumber = 0;

    /**
     * Required. The pair for which the result will count towards their result. 1: NortSouth 2:
     * EastWest 3: For NorthSouth as wel as for EastWest Note: currently split scores (scores different
     * for NS and EW) are not supported. BCS will work with the NS value.
     */
    public int $ScoringDirection = 0;

    /**
     * Marks the result as deleted. All properties below will be ignored.
     */
    public bool $IsDeleted = false;

    /**
     * Required: The pairnumber for NorthSouth
     */
    public int $PairNorthSouth = 0;

    /**
     * Required:The pairnumber for EastWest
     */
    public int $PairEastWest = 0;

    /**
     * Required: either the PairNorthSouth or the PairEastwest number.
     */
    public int $DeclaringPair = 0;

    /**
     * The direction of the declarer: 0: NA 1: North or NorthSouth 2: East or EastWest 3: South 4: West
     */
    public int $DeclarerDirection = 0;

    /**
     * The contract level: 1-7 natural contract 0 Pass -1 Avg-/Avg- -2 Avg-/Avg -3 Avg-/Av+ -4 Avg/Avg-
     * -5 Avg/Avg -6 Avg/Avg+ -7 Avg+/Avg- -8 Avg+/Avg -9 Avg+/Avg+ -10 No play
     */
    public int $Level = 0;

    /**
     * The denomination: 0: NA 1: Clubs 2: Diamonds 3: Hearts 4: Spades 5: NoTrump
     */
    public int $Denomination = 0;

    /**
     * The stake of the contract: 0: normal 1: doubled 2: redoubled
     */
    public int $Stake = 0;

    /**
     * A number between 0 and 13 describing the number of tricks made. Zero tricks can also mean: pass,
     * or artificial result (see Level)
     */
    public int $TotalTricks = 0;

    /**
     * Optional: 2-10: the card value 11: Jack 12: Queen 13: King 14: Ace
     */
    public int $LeadCardRank = 0;

    /**
     * Required when LeadCardRank > 0 1: Clubs 2: Diamonds 3: Hearts 4: Spades
     */
    public int $LeadCardSuit = 0;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'TableNumber' => $this->TableNumber,
            'RoundNumber' => $this->RoundNumber,
            'BoardNumber' => $this->BoardNumber,
            'ScoringDirection' => $this->ScoringDirection,
            'IsDeleted' => $this->IsDeleted,
            'PairNorthSouth' => $this->PairNorthSouth,
            'PairEastWest' => $this->PairEastWest,
            'DeclaringPair' => $this->DeclaringPair,
            'DeclarerDirection' => $this->DeclarerDirection,
            'Level' => $this->Level,
            'Denomination' => $this->Denomination,
            'Stake' => $this->Stake,
            'TotalTricks' => $this->TotalTricks,
            'LeadCardRank' => $this->LeadCardRank,
            'LeadCardSuit' => $this->LeadCardSuit,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->TableNumber = $data['TableNumber'] ?? 0;
        $dto->RoundNumber = $data['RoundNumber'] ?? 0;
        $dto->BoardNumber = $data['BoardNumber'] ?? 0;
        $dto->ScoringDirection = $data['ScoringDirection'] ?? 0;
        $dto->IsDeleted = $data['IsDeleted'] ?? false;
        $dto->PairNorthSouth = $data['PairNorthSouth'] ?? 0;
        $dto->PairEastWest = $data['PairEastWest'] ?? 0;
        $dto->DeclaringPair = $data['DeclaringPair'] ?? 0;
        $dto->DeclarerDirection = $data['DeclarerDirection'] ?? 0;
        $dto->Level = $data['Level'] ?? 0;
        $dto->Denomination = $data['Denomination'] ?? 0;
        $dto->Stake = $data['Stake'] ?? 0;
        $dto->TotalTricks = $data['TotalTricks'] ?? 0;
        $dto->LeadCardRank = $data['LeadCardRank'] ?? 0;
        $dto->LeadCardSuit = $data['LeadCardSuit'] ?? 0;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
