<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * The RoundDTO describes the seating for a round on a table: the NS and EW pairs and the board numbers
 * expressed by the LowBoardNumber and HighBoardNumber properties.
 */
class RoundDTO implements \JsonSerializable
{
    /**
     * Required. The guid of the session the round belongs to.
     */
    public ?string $SessionGuid = null;

    /**
     * Required, the letters of the section.
     */
    public ?string $SectionLetters = null;

    /**
     * Required, must be greater than zero.
     */
    public int $TableNumber = 0;

    /**
     * Required, must be greater than zero.
     */
    public int $RoundNumber = 0;

    /**
     * Optional, can be zero if the table is empty (has no pairs) or is a sit-out (One pair is absent).
     */
    public int $LowBoardNumber = 0;

    /**
     * Optional, can be zero if the table is empty (has no pairs) or is a sit-out (One pair is absent).
     */
    public int $HighBoardNumber = 0;

    /**
     * Required, can be zero if the table is empty or the opponents have a sit-out.
     */
    public int $PairNS = 0;

    /**
     * Required, can be zero if the table is empty or the opponents have a sit-out.
     */
    public int $PairEW = 0;

    /**
     * Optional. The number of the team the NS pair belongs to.
     */
    public int $TeamNS = 0;

    /**
     * Optional. The number of the team the EW pair belongs to.
     */
    public int $TeamEW = 0;

    /**
     * Optional. The letters of the section where the teammates play the same boards. If used the
     * MatesTableNumber and MatesTableRoundNumber properties must be set as well.
     */
    public ?string $MatesTableSectionLetters = null;

    /**
     * Optional. The number of the table where the teammates play the same boards. If used the
     * MatesTableSectionLetters and MatesTableRoundNumber properties must be set as well.
     */
    public int $MatesTableTableNumber = 0;

    /**
     * Optional. The number of the round where the teammates play the same boards. If used the
     * MatesTableSectionLetters and the MatesTableNumber properties must be set as well.
     */
    public int $MatesTableRoundNumber = 0;

    /**
     * Currently not in use for scoring programs. Used for internal administration when handling
     * movement updates.
     */
    public bool $Updated = false;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'TableNumber' => $this->TableNumber,
            'RoundNumber' => $this->RoundNumber,
            'LowBoardNumber' => $this->LowBoardNumber,
            'HighBoardNumber' => $this->HighBoardNumber,
            'PairNS' => $this->PairNS,
            'PairEW' => $this->PairEW,
            'TeamNS' => $this->TeamNS,
            'TeamEW' => $this->TeamEW,
            'MatesTableSectionLetters' => $this->MatesTableSectionLetters,
            'MatesTableTableNumber' => $this->MatesTableTableNumber,
            'MatesTableRoundNumber' => $this->MatesTableRoundNumber,
            'Updated' => $this->Updated,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->TableNumber = $data['TableNumber'] ?? 0;
        $dto->RoundNumber = $data['RoundNumber'] ?? 0;
        $dto->LowBoardNumber = $data['LowBoardNumber'] ?? 0;
        $dto->HighBoardNumber = $data['HighBoardNumber'] ?? 0;
        $dto->PairNS = $data['PairNS'] ?? 0;
        $dto->PairEW = $data['PairEW'] ?? 0;
        $dto->TeamNS = $data['TeamNS'] ?? 0;
        $dto->TeamEW = $data['TeamEW'] ?? 0;
        $dto->MatesTableSectionLetters = $data['MatesTableSectionLetters'] ?? null;
        $dto->MatesTableTableNumber = $data['MatesTableTableNumber'] ?? 0;
        $dto->MatesTableRoundNumber = $data['MatesTableRoundNumber'] ?? 0;
        $dto->Updated = $data['Updated'] ?? false;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
