<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * These enum values comprise the command values that can be set on the ScoringProgramRequest's Command
 * property. Not all of these are currently supported. In the comments after the values the associated
 * Data Transfer Object (DTO) is mentioned if applicable.
 */
enum ScoringProgramDataConnectorCommands: int
{
    /**
     * Invalid, never use
     */
    case None = 0;
    /**
     * Connect to the Data Connector
     */
    case Connect = 1;
    /**
     * Not supported
     */
    case StopBCS = 2;
    /**
     * Disconnects from the Data Connector
     */
    case Disconnect = 3;
    /**
     * Checks if the Data Connnector responds
     */
    case Ping = 4;
    /**
     * Initialize an event with at least one session, its scoringgroups, sections, tables and rounds.
     */
    case InitializeEvent = 5;
    /**
     * Update the movement for a section, or delete the section.
     */
    case UpdateMovement = 6;
    /**
     * Adds a session to a known event.
     */
    case AddSession = 7;
    /**
     * Update the scoringmethod of the scoringgroups and/or rearrange the assignment of the sections to
     * them.
     */
    case UpdateScoringGroups = 8;
    /**
     * Not supported
     */
    case PutTableGraph = 9;
    /**
     * Upload board results to the Data Connector
     */
    case PutResults = 10;
    /**
     * Upload player data to the Data Connector
     */
    case PutPlayerData = 11;
    /**
     * Upload participations to the Data Connector
     */
    case PutParticipations = 12;
    /**
     * Upload handrecords to the Data Connector
     */
    case PutHandrecords = 13;
    /**
     * Upload Bridgemate 2 settings to the Data Connector
     */
    case PutBridgemate2Settings = 14;
    /**
     * Upload Bridgemate 3 settings results to the Data Connector
     */
    case PutBridgemate3Settings = 15;
    /**
     * Not supported
     */
    case UpdateSession = 16;
    /**
     * Not supported
     */
    case UpdateSection = 17;
    /**
     * Not supported
     */
    case UpdateTable = 18;
    /**
     * Query the Data Connector for new board results.
     */
    case PollQueueForNewResults = 19;
    /**
     * Query the Data Connector for new player data.
     */
    case PollQueueForNewPlayerData = 20;
    /**
     * Query the Data Connector for new participations.
     */
    case PollQueueForNewParticipations = 21;
    /**
     * Query the Data Connector for new handrecords.
     */
    case PollQueueForNewHandrecords = 22;
    /**
     * Request all board results for the session from the Data Connector.
     */
    case PollQueueForAllResults = 23;
    /**
     * Request all player data for the session from the Data Connector.
     */
    case PollQueueForAllPlayerData = 24;
    /**
     * Request all participations results for the session from the Data Connector.
     */
    case PollQueueForAllParticipations = 25;
    /**
     * Request all handrecords for the session from the Data Connector.
     */
    case PollQueueForAllHandrecords = 26;
    /**
     * Accept the new board results: the Data Connector will not send them again, unless the
     * PollQueueForAllResults command is used.
     */
    case AcceptResultQueueItems = 27;
    /**
     * Accept the new player data: the Data Connector will not send them again, unless the
     * PollQueueForAllPlayerData command is used.
     */
    case AcceptPlayerDataQueueItems = 28;
    /**
     * Accept the new participations: the Data Connector will not send them again, unless the
     * PollQueueForAllParticipations command is used.
     */
    case AcceptParticipantQueueItems = 29;
    /**
     * Accept the new handrecords: the Data Connector will not send them again, unless the
     * PollQueueForAllHandrecords command is used.
     */
    case AcceptHandrecordQueueItems = 30;
    /**
     * Continue an event that was start before using the InitializeEvent command.
     */
    case ContinueEvent = 31;
    /**
     * Requests the movement for a specific section from the Data Connector.
     */
    case GetMovement = 32;
    /**
     * Requests all movements of a session from the Data Connector
     */
    case GetAllMovements = 33;
    /**
     * Queries BCS for either the running session or all known sessions. Also used to request BCS to
     * shut down.
     */
    case ManageBCS = 34;
    /**
     * Instructs the DataConnector to clear all incoming and outgoing queue data.
     */
    case ClearData = 35;
    /**
     * Query the Data Connector for new td calls.
     */
    case PollQueueForNewTdCalls = 36;
    /**
     * Query the Data Connector for all td calls.
     */
    case PollQueueForAllTdCalls = 37;
    /**
     * Accept the new td calls: the Data Connector will not send them again, unless the
     * PollQueueForAllTdCalls command is used.
     */
    case AcceptTdCallQueueItems = 38;
    /**
     * Upload td calls to the Data Connector
     */
    case PutTdCalls = 39;
    /**
     * Not supported
     */
    case TestData = 40;
}
