<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * This class carries both a command and its associated data (if any) for the Data Connector. If the
 * command pertains to a specific session the SessionGuid property has to be set. Validation will check
 * in that case if the SessionGuid properties of the SerializedData has the same value. The Data
 * Connector always responds with a ScoringProgramResponse
 */
class ScoringProgramRequest implements \JsonSerializable
{
    /**
     * Required. The command that the Data Connector must pass on to BCS.
     */
    public ScoringProgramDataConnectorCommands $Command = ScoringProgramDataConnectorCommands::None;

    /**
     * Required when using the http interface for the dataconnector
     */
    public ?string $ClubId = null;

    /**
     * Required when using the http interface for the dataconnector
     */
    public ?string $LicenceKey = null;

    /**
     * Required if the command pertains to a session. Must be empty otherwise.
     */
    public ?string $SessionGuid = null;

    /**
     * The data associated with the command, if any. Must be serialized as JSON.
     */
    public ?string $SerializedData = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'Command' => $this->Command,
            'ClubId' => $this->ClubId,
            'LicenceKey' => $this->LicenceKey,
            'SessionGuid' => $this->SessionGuid,
            'SerializedData' => $this->SerializedData,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->Command = ScoringProgramDataConnectorCommands::tryFrom($data['Command'] ?? 0) ?? ScoringProgramDataConnectorCommands::None;
        $dto->ClubId = $data['ClubId'] ?? null;
        $dto->LicenceKey = $data['LicenceKey'] ?? null;
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SerializedData = $data['SerializedData'] ?? null;
        return $dto;
    }
}
