<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * The scoring group holds information on the scoring method of its sections. A scoring group must have
 * at least one section, though this can be omitted when using this DTO for scoring group updates. If a
 * scoring group has more than one section the score calculation will treat these sections as if they
 * were one.
 */
class ScoringGroupDTO implements \JsonSerializable
{
    /**
     * The matchscore is expressed in matchpoints.
     */
    public const ScoringType_Pairs = 10;

    /**
     * The matchscore is expressed in Butler Imps with Avg+ as +2 and weighted datescore calculation.
     */
    public const ScoringType_Imp2_Weighted = 20;

    /**
     * The matchscore is expressed in Butler Imps with Avg+ as +2 and 10% omit datescore calculation.
     */
    public const ScoringType_Imp2_10Percent = 21;

    /**
     * The matchscore is expressed in Butler Imps with Avg+ as +2 and no correection for datescore
     * calculation.
     */
    public const ScoringType_Imp2_NoCorrection = 22;

    /**
     * The matchscore is expressed in Butler Imps with Avg+ as +3 and weighted datescore calculation.
     */
    public const ScoringType_Imp3_Weighted = 25;

    /**
     * The matchscore is expressed in Butler Imps with Avg+ as +3 and 10% omit datescore calculation.
     */
    public const ScoringType_Imp3_10Percent = 26;

    /**
     * The matchscore is expressed in Butler Imps with Avg+ as +2 and no correection for datescore
     * calculation.
     */
    public const ScoringType_Imp3_NoCorrection = 27;

    /**
     * The matchscore is expressed in Cross Imps total IMPs.The Avg+=+2 IMP.
     */
    public const ScoringType_XImp2_Total = 30;

    /**
     * The matchscore is expressed in Cross Imps average IMPs.The Avg+=+2 IMP.
     */
    public const ScoringType_XImp2_Average = 31;

    /**
     * The matchscore is expressed in Cross Imps total IMPs.The Avg+=+3 IMP.
     */
    public const ScoringType_XImp3_Total = 35;

    /**
     * The matchscore is expressed in Cross Imps average IMPs.The Avg+=+3 IMP.
     */
    public const ScoringType_XImp3_Average = 36;

    /**
     * The matchscore is expressed in Team Imps.
     */
    public const ScoringType_TeamImps = 40;

    /**
     * The matchscore is expressed in discrete (whole number) Victory Points.
     */
    public const ScoringType_TeamVPDiscrete = 50;

    /**
     * The matchscore is expressed in continuous (floating point) Victory Points.
     */
    public const ScoringType_TeamVPContinuous = 51;

    /**
     * The matchscore is expressed in Board-a-Match points.
     */
    public const ScoringType_Bam = 60;

    /**
     * The matchscore is expressed as a Patton score.
     */
    public const ScoringType_Patton = 70;

    /**
     * Required, must match the Guid of its SessionDTO parent.
     */
    public ?string $SessionGuid = null;

    /**
     * Required when using http for communication with the data connector.
     */
    public ?string $ClubId = null;

    /**
     * Required when the dto is part of the InitDTO, must be at least one. Optional when the dto is
     * used for scoringgroup updates. Must be empty if the IsDeleted property is true.
     * @var SectionDTO[]|null
     */
    public ?array $Sections = null;

    /**
     * Required, must be unique and greater than zero.
     */
    public int $ScoringGroupNumber = 0;

    /**
     * Required. Pairs = 10, IMP = 20, XIMP = 30, TeamIMP = 40, TeamsVPDiscrete = 50, TeamsVPContinuous
     * = 51, Bam = 60, Patton = 70
     */
    public int $ScoringMethod = 0;

    /**
     * Optional
     */
    public ?string $Name = null;

    /**
     * If "True" the scoring group will be deleted if it has no more sections. Be sure to assign other
     * scoring groups to this scoringgroup's sections if its sections are not deleted. Will be ignored
     * when the dto is part of the InitDTO.
     */
    public bool $IsDeleted = false;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'ClubId' => $this->ClubId,
            'Sections' => $this->Sections,
            'ScoringGroupNumber' => $this->ScoringGroupNumber,
            'ScoringMethod' => $this->ScoringMethod,
            'Name' => $this->Name,
            'IsDeleted' => $this->IsDeleted,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->ClubId = $data['ClubId'] ?? null;
        $dto->Sections = isset($data['Sections']) ? array_map(static fn (array $item): SectionDTO => SectionDTO::fromArray($item), $data['Sections']) : null;
        $dto->ScoringGroupNumber = $data['ScoringGroupNumber'] ?? 0;
        $dto->ScoringMethod = $data['ScoringMethod'] ?? 0;
        $dto->Name = $data['Name'] ?? null;
        $dto->IsDeleted = $data['IsDeleted'] ?? false;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
