<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * This class carries the response data that the Data Connector sends back after sending it a
 * ScoringProgramRequest.
 */
class ScoringProgramResponse implements \JsonSerializable
{
    /**
     * The command of the request that this is the reponse for.
     */
    public ScoringProgramDataConnectorCommands $RequestCommand = ScoringProgramDataConnectorCommands::None;

    /**
     * Specifies the datatype to deserialize to after reception of the response.
     * DataConnectorResponseData.Error signals that something went wrong. The serialized data in that
     * case will be a string describing the error.
     */
    public DataConnectorResponseData $DataType = DataConnectorResponseData::None;

    /**
     * If the response contains queue data the id of last added queueitem.
     */
    public int $LastQueueItemId = 0;

    /**
     * Specifies the type of error that occurred. ErrorType.None if all went well.
     */
    public ErrorType $ErrorType = ErrorType::None;

    /**
     * The guid of the session the response belongs to.
     */
    public ?string $SessionGuid = null;

    /**
     * The serialized data. The DataType property tells to what class it should be deserialized.
     */
    public ?string $SerializedData = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'RequestCommand' => $this->RequestCommand,
            'DataType' => $this->DataType,
            'LastQueueItemId' => $this->LastQueueItemId,
            'ErrorType' => $this->ErrorType,
            'SessionGuid' => $this->SessionGuid,
            'SerializedData' => $this->SerializedData,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->RequestCommand = ScoringProgramDataConnectorCommands::tryFrom($data['RequestCommand'] ?? 0) ?? ScoringProgramDataConnectorCommands::None;
        $dto->DataType = DataConnectorResponseData::tryFrom($data['DataType'] ?? 0) ?? DataConnectorResponseData::None;
        $dto->LastQueueItemId = $data['LastQueueItemId'] ?? 0;
        $dto->ErrorType = ErrorType::tryFrom($data['ErrorType'] ?? 0) ?? ErrorType::None;
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SerializedData = $data['SerializedData'] ?? null;
        return $dto;
    }
}
