<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * This class is a container for participants that can potentially meet each other during the session.
 * Their results will be compared and they will be ranked against each other. Note: if the section is
 * part of a scoringgroup together with an other section the scoring calculation will treat these
 * sections as one.
 */
class SectionDTO implements \JsonSerializable
{
    /**
     * The section hosts a pairs competition. Rankings will be for each pair.
     */
    public const GameType_Pairs = 10;

    /**
     * The section hosts an individual competition. Rankings will be for each player.
     */
    public const GameType_Individual = 20;

    /**
     * The section hosts a teams competition. Rankings will be for each teams (although a parallel
     * pairs ranking is possible).
     */
    public const GameType_Teams = 30;

    /**
     * Required. The guid of the session the section is part of. A string built from a Guid, without
     * the curly braces or connecting dashes. The letters must be capitals
     */
    public ?string $SessionGuid = null;

    /**
     * Required, the number of the scoringgroup the section belongs to. Must be greater than zero.
     */
    public int $ScoringGroupNumber = 0;

    /**
     * Required. The letters of the section. They must be unique within an event. Can be A-Z, AA, BB,
     * CC,...ZZ, AAA, BBB, CCC, ... ZZZ
     */
    public ?string $Letters = null;

    /**
     * Optional.
     */
    public ?string $Name = null;

    /**
     * Required: either 1 or 2.
     */
    public int $Winners = 0;

    public int $GameType = 0;

    /**
     * Negative value: the eastwest pairs move down the specified number of tables before play starts.
     * Positive value: the eastwest pairs move up the specified number of tables before play starts.
     * Zero: the eastwest pairs do not move. Currently not supported.
     */
    public int $EWMoveBeforePlay = 0;

    /**
     * Optional. A pair that is missing throughout the movement. Alternatively this can be specified by
     * Leaving out the opponent for a pair that would have met the missing pair. However, BCS will be
     * able to discern a sit-out table from an empty table if this value is used. When using a two
     * winner movement a positive number denotes a missing NS pair, a negative value denotes a missing
     * EW pair.
     */
    public int $MissingPair = 0;

    /**
     * When "true" the Bridgemate (2) server will be instructed to net close the session when the
     * result for the last available round have been received. In this way it is possible to play Swiss
     * matches.
     */
    public bool $KeepBridgematesAlive = false;

    /**
     * If true the NorthSouthPairSectionLetters and the EastWestPairSectionLetters must have the value
     * for an existing section.
     */
    public bool $IsCombiSection = false;

    /**
     * Required if IsCombiSection is True. Must be the letters for an existing section. The letters of
     * the section the North-South pairs in the combisection originate from.
     */
    public ?string $NorthSouthPairSectionLetters = null;

    /**
     * Required if IsCombisection is True. Must be the letters for an existing section. The letters of
     * the section the East-West pairs in the combisection originate from.
     */
    public ?string $EastWestPairSectionLetters = null;

    /**
     * An array of TableDTOs. All tables for the section must be specified.
     * @var TableDTO[]|null
     */
    public ?array $Tables = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'ScoringGroupNumber' => $this->ScoringGroupNumber,
            'Letters' => $this->Letters,
            'Name' => $this->Name,
            'Winners' => $this->Winners,
            'GameType' => $this->GameType,
            'EWMoveBeforePlay' => $this->EWMoveBeforePlay,
            'MissingPair' => $this->MissingPair,
            'KeepBridgematesAlive' => $this->KeepBridgematesAlive,
            'IsCombiSection' => $this->IsCombiSection,
            'NorthSouthPairSectionLetters' => $this->NorthSouthPairSectionLetters,
            'EastWestPairSectionLetters' => $this->EastWestPairSectionLetters,
            'Tables' => $this->Tables,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->ScoringGroupNumber = $data['ScoringGroupNumber'] ?? 0;
        $dto->Letters = $data['Letters'] ?? null;
        $dto->Name = $data['Name'] ?? null;
        $dto->Winners = $data['Winners'] ?? 0;
        $dto->GameType = $data['GameType'] ?? 0;
        $dto->EWMoveBeforePlay = $data['EWMoveBeforePlay'] ?? 0;
        $dto->MissingPair = $data['MissingPair'] ?? 0;
        $dto->KeepBridgematesAlive = $data['KeepBridgematesAlive'] ?? false;
        $dto->IsCombiSection = $data['IsCombiSection'] ?? false;
        $dto->NorthSouthPairSectionLetters = $data['NorthSouthPairSectionLetters'] ?? null;
        $dto->EastWestPairSectionLetters = $data['EastWestPairSectionLetters'] ?? null;
        $dto->Tables = isset($data['Tables']) ? array_map(static fn (array $item): TableDTO => TableDTO::fromArray($item), $data['Tables']) : null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
