<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Contains information for an updated or added section
 */
class SectionUpdateDTO implements \JsonSerializable
{
    /**
     * Required. The guid of the session the section is part of. A string built from a Guid, without
     * the curly braces or connecting dashes. The letters must be capitals
     */
    public ?string $SessionGuid = null;

    /**
     * Required when using the http interface for the dataconnector
     */
    public ?string $ClubId = null;

    /**
     * Required, the number of the scoringgroup the section belongs to. Must be greater than zero. If
     * the scoringgroup already exists the section wull be added to it, otherwise a new scoringgroup
     * wil be added.
     */
    public int $ScoringGroupNumber = 0;

    /**
     * Must be set and must match the scoringmethod of the scoringgroup if the section is added to one,
     * otherwise it will specify the scoringmethod for the new scoringgroup. See for valid values the
     * ScoringType contstants in the ScoringGroupDTO.
     */
    public int $ScoringGroupScoringMethod = 0;

    /**
     * Required. The letters of the section. If a section with this letters already exists it will be
     * updated. Otherwise the section will be added. Can be A-Z, AA, BB, CC,...ZZ, AAA, BBB, CCC, ...
     * ZZZ
     */
    public ?string $Letters = null;

    /**
     * Optional.
     */
    public ?string $Name = null;

    /**
     * Required: either 1 or 2.
     */
    public int $Winners = 0;

    public int $GameType = 0;

    /**
     * Negative value: the eastwest pairs move down the specified number of tables before play starts.
     * Positive value: the eastwest pairs move up the specified number of tables before play starts.
     * Zero: the eastwest pairs do not move. Currently not supported.
     */
    public int $EWMoveBeforePlay = 0;

    /**
     * Optional. A pair that is missing throughout the movement. Alternatively this can be specified by
     * Leaving out the opponent for a pair that would have met the missing pair. However, BCS will be
     * able to discern a sit-out table from an empty table if this value is used. When using a two
     * winner movement a positive number denotes a missing NS pair, a negative value denotes a missing
     * EW pair.
     */
    public int $MissingPair = 0;

    /**
     * When "true" the Bridgemate (2) server will be instructed to net close the session when the
     * result for the last available round have been received. In this way it is possible to play Swiss
     * matches.
     */
    public bool $KeepBridgematesAlive = false;

    /**
     * If true the SitoutSectionLetters must have the value for an existing section.
     */
    public bool $IsCombiSection = false;

    /**
     * Required if IsCombiSection is True. Must be the letters for an existing section. The letters of
     * the section the North-South pairs in the combisection originate from.
     */
    public ?string $NorthSouthPairSectionLetters = null;

    /**
     * Required if IsCombisection is True. Must be the letters for an existing section. The letters of
     * the section the East-West pairs in the combisection originate from.
     */
    public ?string $EastWestPairSectionLetters = null;

    /**
     * Marks the section for deletion. No tables must be specified. ALl properties other than the
     * SessionGuid an Letters are ignored.
     */
    public bool $IsDeleted = false;

    /**
     * Optional. Any players that have been added and were not included while initializing the session.
     * @var PlayerDataDTO[]|null
     */
    public ?array $AddedPlayers = null;

    /**
     * Optional. The players as they are seated in the first round. Be sure to include players as well
     * that do not play in the first round.
     * @var ParticipationDTO[]|null
     */
    public ?array $Participations = null;

    /**
     * An array of TableDTOs. All tables for the section must be specified. If the section is to be
     * deleted, no tables must be specified.
     * @var TableDTO[]|null
     */
    public ?array $Tables = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'ClubId' => $this->ClubId,
            'ScoringGroupNumber' => $this->ScoringGroupNumber,
            'ScoringGroupScoringMethod' => $this->ScoringGroupScoringMethod,
            'Letters' => $this->Letters,
            'Name' => $this->Name,
            'Winners' => $this->Winners,
            'GameType' => $this->GameType,
            'EWMoveBeforePlay' => $this->EWMoveBeforePlay,
            'MissingPair' => $this->MissingPair,
            'KeepBridgematesAlive' => $this->KeepBridgematesAlive,
            'IsCombiSection' => $this->IsCombiSection,
            'NorthSouthPairSectionLetters' => $this->NorthSouthPairSectionLetters,
            'EastWestPairSectionLetters' => $this->EastWestPairSectionLetters,
            'IsDeleted' => $this->IsDeleted,
            'AddedPlayers' => $this->AddedPlayers,
            'Participations' => $this->Participations,
            'Tables' => $this->Tables,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->ClubId = $data['ClubId'] ?? null;
        $dto->ScoringGroupNumber = $data['ScoringGroupNumber'] ?? 0;
        $dto->ScoringGroupScoringMethod = $data['ScoringGroupScoringMethod'] ?? 0;
        $dto->Letters = $data['Letters'] ?? null;
        $dto->Name = $data['Name'] ?? null;
        $dto->Winners = $data['Winners'] ?? 0;
        $dto->GameType = $data['GameType'] ?? 0;
        $dto->EWMoveBeforePlay = $data['EWMoveBeforePlay'] ?? 0;
        $dto->MissingPair = $data['MissingPair'] ?? 0;
        $dto->KeepBridgematesAlive = $data['KeepBridgematesAlive'] ?? false;
        $dto->IsCombiSection = $data['IsCombiSection'] ?? false;
        $dto->NorthSouthPairSectionLetters = $data['NorthSouthPairSectionLetters'] ?? null;
        $dto->EastWestPairSectionLetters = $data['EastWestPairSectionLetters'] ?? null;
        $dto->IsDeleted = $data['IsDeleted'] ?? false;
        $dto->AddedPlayers = isset($data['AddedPlayers']) ? array_map(static fn (array $item): PlayerDataDTO => PlayerDataDTO::fromArray($item), $data['AddedPlayers']) : null;
        $dto->Participations = isset($data['Participations']) ? array_map(static fn (array $item): ParticipationDTO => ParticipationDTO::fromArray($item), $data['Participations']) : null;
        $dto->Tables = isset($data['Tables']) ? array_map(static fn (array $item): TableDTO => TableDTO::fromArray($item), $data['Tables']) : null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
