<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * A group of sections that are usually played at the same time and place. Pairs will subscribe to
 * participate in a specific session. If BCS has to administer more than one session at the same time,
 * these sessions must share a comment EventGuid property.
 */
class SessionDTO implements \JsonSerializable
{
    /**
     * Required, must be at least one.
     * @var ScoringGroupDTO[]|null
     */
    public ?array $ScoringGroups = null;

    /**
     * Optional. A string built from a Guid, without the curly braces or connecting dashes. The letters
     * must be capitals Must be unique if used.
     */
    public ?string $EventGuid = null;

    /**
     * Required.A string built from a Guid, without the curly braces or connecting dashes. The letters
     * must be capitals Must be unique
     */
    public ?string $SessionGuid = null;

    /**
     * Required. The name of the session.
     */
    public ?string $Name = null;

    /**
     * Required. The year in which the session is played.
     */
    public int $Year = 0;

    /**
     * Required. The month in which the session is played.
     */
    public int $Month = 0;

    /**
     * Required. The day on which the session is played.
     */
    public int $Day = 0;

    /**
     * Optional. The starting hour for the session.
     */
    public int $Hour = 0;

    /**
     * Optional. The starting minutes for the session.
     */
    public int $Minute = 0;

    /**
     * If True will show the session in the Bridgemate App, if the Bridgemae App has been configured in
     * BCS.
     */
    public bool $ShowInApp = false;

    public bool $EWReturnHome = false;

    public bool $PairsMoveAccrossField = false;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'ScoringGroups' => $this->ScoringGroups,
            'EventGuid' => $this->EventGuid,
            'SessionGuid' => $this->SessionGuid,
            'Name' => $this->Name,
            'Year' => $this->Year,
            'Month' => $this->Month,
            'Day' => $this->Day,
            'Hour' => $this->Hour,
            'Minute' => $this->Minute,
            'ShowInApp' => $this->ShowInApp,
            'EWReturnHome' => $this->EWReturnHome,
            'PairsMoveAccrossField' => $this->PairsMoveAccrossField,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->ScoringGroups = isset($data['ScoringGroups']) ? array_map(static fn (array $item): ScoringGroupDTO => ScoringGroupDTO::fromArray($item), $data['ScoringGroups']) : null;
        $dto->EventGuid = $data['EventGuid'] ?? null;
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->Name = $data['Name'] ?? null;
        $dto->Year = $data['Year'] ?? 0;
        $dto->Month = $data['Month'] ?? 0;
        $dto->Day = $data['Day'] ?? 0;
        $dto->Hour = $data['Hour'] ?? 0;
        $dto->Minute = $data['Minute'] ?? 0;
        $dto->ShowInApp = $data['ShowInApp'] ?? false;
        $dto->EWReturnHome = $data['EWReturnHome'] ?? false;
        $dto->PairsMoveAccrossField = $data['PairsMoveAccrossField'] ?? false;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
