<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * A class describing a real or virtual bridge table where each round two pairs will compete.
 */
class TableDTO implements \JsonSerializable
{
    /**
     * Required. The guid of the session the table belongs to.
     */
    public ?string $SessionGuid = null;

    /**
     * Required, the letters of the section the table belongs to. The section must exist.
     */
    public ?string $SectionLetters = null;

    /**
     * Required, must be greater than zero and must be unique within the section.
     */
    public int $TableNumber = 0;

    /**
     * Optional: specifies if the Bridgemate on the table should work in online mode (default) or
     * offline mode. In offline mode the Bridgemate will not communicate with the Bridgemate 3 server
     * during the session, but will try to send its results after the last board had been played.
     * Because of this the Bridgemate will not respond to movement updates. Mind: this setting will
     * only have effect when the Bridgemate first connects to the session. Once a Bridgemate has been
     * initialized with movement data the ConnectionMode cannot be changed until the Bridgemate is
     * restarted.
     */
    public Bm3ConnectionModeOption $ConnectionMode = Bm3ConnectionModeOption::Online;

    /**
     * If set to "True" the Bridgemates will await new rounddata after all results have been entered
     * for the existing rounds on the tables. Otherwise, by default, the Bridgemate will signal end of
     * session when all the results its expects have been entered.
     */
    public bool $KeepBridgematesAlive = false;

    /**
     * Required. An array of RoundDTOs describing which pairs will meet on this table and which boards
     * they will play.
     * @var RoundDTO[]|null
     */
    public ?array $Rounds = null;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'TableNumber' => $this->TableNumber,
            'ConnectionMode' => $this->ConnectionMode,
            'KeepBridgematesAlive' => $this->KeepBridgematesAlive,
            'Rounds' => $this->Rounds,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->TableNumber = $data['TableNumber'] ?? 0;
        $dto->ConnectionMode = Bm3ConnectionModeOption::tryFrom($data['ConnectionMode'] ?? 0) ?? Bm3ConnectionModeOption::Online;
        $dto->KeepBridgematesAlive = $data['KeepBridgematesAlive'] ?? false;
        $dto->Rounds = isset($data['Rounds']) ? array_map(static fn (array $item): RoundDTO => RoundDTO::fromArray($item), $data['Rounds']) : null;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
