<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Specifies the positions on a table.
 */
enum TableDirection: int
{
    /**
     * No position specified.
     */
    case None = 0;
    /**
     * North
     */
    case North = 1;
    /**
     * East
     */
    case East = 2;
    /**
     * South
     */
    case South = 3;
    /**
     * West
     */
    case West = 4;
}
