<?php

declare(strict_types=1);

// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.

namespace Bridgemate\DataConnector\Dto;

/**
 * Contains information about a TD call.
 */
class TdCallDTO implements \JsonSerializable
{
    /**
     * The TD call status has been iniiated.
     */
    public const TdCallStatus_Launched = 1;

    /**
     * The TD is at the table.
     */
    public const TdCallStatus_InProgress = 2;

    /**
     * The call has been resolved.
     */
    public const TdCallStatus_Resolved = 3;

    /**
     * Resolution of the call has been deferred.
     */
    public const TdCallStatus_Deferred = 4;

    /**
     * Required. The guid of the session the td call belongs to.
     */
    public ?string $SessionGuid = null;

    /**
     * Required, the letters of the section the td call belongs to. The section must exist.
     */
    public ?string $SectionLetters = null;

    /**
     * Required, the table in the section where the td call originates from.
     */
    public int $TableNumber = 0;

    /**
     * Required. The round om the table where the td call is generated from.
     */
    public int $RoundNumber = 0;

    /**
     * The hour at which the td call was generated. Use 24 hours to a day.
     */
    public int $Hour = 0;

    /**
     * The minute in which the td call was generated.
     */
    public int $Minute = 0;

    /**
     * Required. Valid values are: 1: Launched 2: InProgress 3. Resolved 4: Deferred
     */
    public int $Status = 0;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     * @var string[]|null
     */
    public ?array $ValidationMessages = null;

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return [
            'SessionGuid' => $this->SessionGuid,
            'SectionLetters' => $this->SectionLetters,
            'TableNumber' => $this->TableNumber,
            'RoundNumber' => $this->RoundNumber,
            'Hour' => $this->Hour,
            'Minute' => $this->Minute,
            'Status' => $this->Status,
            'ValidationMessages' => $this->ValidationMessages,
        ];
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        $dto = new self();
        $dto->SessionGuid = $data['SessionGuid'] ?? null;
        $dto->SectionLetters = $data['SectionLetters'] ?? null;
        $dto->TableNumber = $data['TableNumber'] ?? 0;
        $dto->RoundNumber = $data['RoundNumber'] ?? 0;
        $dto->Hour = $data['Hour'] ?? 0;
        $dto->Minute = $data['Minute'] ?? 0;
        $dto->Status = $data['Status'] ?? 0;
        $dto->ValidationMessages = $data['ValidationMessages'] ?? null;
        return $dto;
    }
}
